### ISSUE TITLE
mobile footer is not styled

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/digitalstrategie#115]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** The footer looks like there should be dropdowns for mobile, but they are not clickable. 
**important screensize:**
**device & browser:** 
**Comment/Question:** I just copied the markup from their example. Do we use the dropdown js from bootstrap along with it?

Screenshot?
![Screenshot from 2021-10-25 13-12-46](https://user-images.githubusercontent.com/8178179/138687976-e55fa71e-97dd-455e-8e96-d02acce924e1.png)
![Screenshot from 2021-10-25 13-12-08](https://user-images.githubusercontent.com/8178179/138687983-121574bd-c8a1-4ea3-bbe0-82b0fd4aa52a.png)

**Comment by phillimorland** [comment]
NOTE: response has been that footer will work after refresh when entering responsive mode, apparently that is not a bug. This is true for the lower footer but content footer still expanded, same is true for first link on their tester and live sites?! will investigate further
