### ISSUE TITLE
Proper error message for 500 error when creating duplicate titled page

### ISSUE THREAD

**Issue by sabinammm** [liqd/digitalstrategie#140]
**URL:** 
**user:** Admin
**expected behaviour:** When I accidentally try to create a page with a title of an existing page, I need an error message that will tell me exactly what I did wrong.
**behaviour:** Instead I get a 500 error page
**important screensize:** any
**device & browser:** ubuntu chrome
**Comment/Question:** 

Screenshot
![500](https://user-images.githubusercontent.com/17978375/138830209-4731b04e-9a91-4db7-9e63-dace2f0cd6fc.png)
?

**Comment by philli-m** [comment]
@fuzzylogic2000 where is that error shown and is there something to be done here?

**Comment by fuzzylogic2000** [comment]
I guess, I tried it locally. But seems to be a wagtail problem. Might be fixed now?! 
Yes, I did check. In the meta tags tab, it says that te slug is already in use and instead of a 500 that is the validation error.
