### ISSUE TITLE
#4899 UX/UI Test - text with image block

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#167]
**URL:** https://digitalstrategie-dev.liqd.net/
**important screensize:** *Mobile*
**Comment/Question:** *Can we also add the CTA on Mobile and make the padding bigger between the Image + text? Sorry, I know that the mobile version was missing on Zeplin idk why but I'll add here* 

Current Status: 
![IMG_7261](https://user-images.githubusercontent.com/59610786/139244137-0eaa26b1-6403-469c-a41a-27e51ba3408c.PNG)

Design: 
![Screenshot 2021-10-28 at 13 03 07](https://user-images.githubusercontent.com/59610786/139243998-577e7509-0c2e-4627-ba4f-f6de1c4d1e57.png)

Thanks!

**Comment by fuzzylogic2000** [comment]
@hmkay @maxliqd The image CTA block is going to restyled, so this issue can be closed, right?

**Comment by hmkay** [comment]
Hello @fuzzylogic2000 , I guess so, but maybe @mcastro-lqd can have the final say in this? =)

**Comment by fuzzylogic2000** [comment]
:tada:
