### ISSUE TITLE
Why / How / Who strips go over header

### ISSUE THREAD

**Issue by rilanari** [liqd/digitalstrategie#168]
**URL:** https://digitalstrategie-dev.liqd.net/
 https://digitalstrategie-dev.liqd.net/faq/
**user:** USER
**expected behaviour:** 
**behaviour:** The little Why / How / Who strip in the Landingpage and the FAQ go over the header when displayed and scrolling down
**important screensize:** Both
**device & browser:** - Google Crome Version 95.0.4638.54
- Firefox 93.0 (64-bit)
- Safari Version 14.1.2 (16611.3.10.1.3)
- Iphone
**Comment/Question:** 

Screenshot?

<img width="978" alt="1 1Screenshot 2021-10-28 at 13 10 43" src="https://user-images.githubusercontent.com/77740788/139261629-428a1ae6-7f73-4f87-9b29-20ede104ed86.png">
<img width="1221" alt="1 2" src="https://user-images.githubusercontent.com/77740788/139261639-3a0052c9-38b0-4e69-8ec0-63de61b8305e.png">
<img width="1054" alt="1 3" src="https://user-images.githubusercontent.com/77740788/139261647-87f751a6-c0af-41ee-bfb2-6ed708c03d82.png">

**Comment by phillimorland** [comment]
@hmkay @maxliqd this will be fixed when we re-write the faq block template to use their templating guidlines (as much as possible) I assume there will be stories for this like with cta teaser block?

**Comment by phillimorland** [comment]
@hmkay faq is a block that can be added to home page, detail and grunbuch, as such it better to keep the stories seperated. Page templates mostly have very little on, I think the grid update means that the simple page template and the detail page template are now in keeping with the style guide with no extra work, but the content block templates should be done seperatly or it gets confusing

**Comment by hmkay** [comment]
Ok! I wrote a story, very simple, and linked it to this issue: https://taiga.liqd.net/project/berlin-digitization-strategy/us/74?no-milestone=1

Are any other blocks still missing? I couldn´find any apart from the quote, but we will do that later. Are the paragraphs done?

**Comment by phillimorland** [comment]
I'm not sure I know what you mean? here is a list of the blocks we have with what pages they can be added, they will use the same template no matter which page they appear on so it only needs to be changed once. The blocks we currently have that have a template that should be updated: 
Call to action - Home
FAQ accordion - Home, Detail, Grunbuch 
Quote - Home
Text with image - Home
Teaser 2 columns - Overview
Teaser image - Overview

Ones which are already using a new template:
Teaser centered - Overview - already using updated template
Theses - Home - already using updated template

**Comment by hmkay** [comment]
Nice, thanks, @phillimorland ! @mcastro-lqd is just doing an overview of all the modules, so this helps. We will need stories for all the templates that should be updated. Or we put it in one story, depending what´s easiest. First we have to talk to them again, though. @mcastro-lqd does that help?

Also FYI @maxliqd

**Comment by phillimorland** [comment]
as there is a story for this, I will now close it
