### ISSUE TITLE
Accesibility: acustic description of content

### ISSUE THREAD

**Issue by rilanari** [liqd/digitalstrategie#172]
**user:** _User_
**expected behaviour:**  _Accesibility // There should be an acustic description of the page content_
**important screensize:** _Both_
**Comment/Question:** _Hello dev team! I made this issue just to have accessibility criteria in Github, I know this is not yet implemented! Thanks !_

**Comment by fuzzylogic2000** [comment]
@hmkay @maxliqd I think, we can close this issue? We do look out for their a11y-criteria and also have a story for the alt-texts.

**Comment by hmkay** [comment]
@fuzzylogic2000 Yes, thank you! I will close it!
