### ISSUE TITLE
Accesibility: Keyboard operability

### ISSUE THREAD

**Issue by rilanari** [liqd/digitalstrategie#173]
**expected behaviour:** _Accesibility // There should be the possibility to type without a keyboard_
**important screensize:** _Both_
**Comment/Question:** _Hello dev team! I made this issue just to have the accessibility criteria in Github, I know this is not yet implemented! Thanks !_

**Comment by rilanari** [comment]
Oh, sorry, maybe I was a bit confused with the list of criteria for testing. Is there a way to know the accessibility things that do not fall in our scope? 
Should we close this issue? 
@fuzzylogic2000 @hmkay 
Thanks!

**Comment by hmkay** [comment]
Maybe it would be nice to know how people deal with voice input - which tools they are using e.g. and what these tools need to be able to insert it. I guess that would be a good point! So if you @rilanari take it with you as a research question, I think we can close it for now.

**Comment by rilanari** [comment]
Great! I will do research on that and close the issue!
