### ISSUE TITLE
#4853 UX/UI Test - Blocks - Image block image not big enough

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#174]
**URL:** https://digitalstrategie-dev.liqd.net/ergebinsse/
**important screensize:** *Both*
**device & browser:** *Safari*
**Comment/Question:** *Tbh I didn't understand this block. The image is off and the Blog Posts were supposed to be different than that, but I imagine that this wasn't implemented yet.*

How it should look like:
![Screenshot 2021-10-28 at 15 53 42](https://user-images.githubusercontent.com/59610786/139270120-2f7b18fe-7f9e-4442-81c2-90c2727e02fa.png)

Current version:
<img width="1531" alt="Screenshot 2021-10-28 at 15 54 31" src="https://user-images.githubusercontent.com/59610786/139270277-02f3f018-b011-4ae7-bf07-5a76da232e73.png">

**Comment by fuzzylogic2000** [comment]
This issue will stay even when we restyle. Can we add the link to the image CTA story, so we don't forget? @hmkay @maxliqd

**Comment by hmkay** [comment]
Yes, done, @fuzzylogic2000 , it is here: https://taiga.liqd.net/project/liqd-liquid-software/us/5299?no-milestone=1

**Comment by phillimorland** [comment]
@fuzzylogic2000 @hmkay this issue is not there after restyle as we do not place image there and it will not need stretching so will close
