### ISSUE TITLE
#4853 UX/UI Test - Blocks - mobile image block image padding

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#175]
**URL:** https://digitalstrategie-dev.liqd.net/mitmachen/
**important screensize:** *Mobile*
**device & browser:** *Safari*
**Comment/Question:** *Is it possible to center this text vertically?*

Design: 
![Screenshot 2021-10-28 at 15 56 46](https://user-images.githubusercontent.com/59610786/139270930-6d8634fd-05aa-4f6b-9955-4f00b7505d3c.png)

Current version:
![IMG_7262](https://user-images.githubusercontent.com/59610786/139271079-31d97dc4-25f1-4736-865f-fa05242c7ee4.jpg)

**Comment by fuzzylogic2000** [comment]
I think this can also be closed because will  be restyled. @maxliqd @hmkay

**Comment by hmkay** [comment]
What do you think, @mcastro-lqd ? I guess that would be your decision...

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Yes, the styling is different so It doesn't make much sense anymore

**Comment by fuzzylogic2000** [comment]
You can open a new with one with new things when we are done. :upside_down_face:
