### ISSUE TITLE
#4853 UX/UI Test - Blocks Missing

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#176]
**URL:** https://digitalstrategie-dev.liqd.net/
**important screensize:** *Both*
**device & browser:** *Safari*
**Comment/Question:** *I guess some of the blocks weren't implemented yet but I'll leave them here just in case.* 

Linking to blog articles: 
![Screenshot 2021-10-28 at 16 01 01](https://user-images.githubusercontent.com/59610786/139271527-6ee8ec33-5b57-4d2c-921d-866dd8631d93.png)

Linking to different websites:
![Screenshot 2021-10-28 at 16 00 48](https://user-images.githubusercontent.com/59610786/139271537-f34c4eb2-2a81-4b16-b0ff-1db03bc74124.png)

This one is similar, if they can live with the other ones im good, but there was the other option using shorter description and font 24: 
![Screenshot 2021-10-28 at 16 00 38](https://user-images.githubusercontent.com/59610786/139271543-3f4f254f-3c38-41c7-889e-0fe54b7c6764.png)

**Comment by fuzzylogic2000** [comment]
@hmkay @maxliqd Can this also be closed as there are new stories for blocks?

**Comment by hmkay** [comment]
@mcastro-lqd what do you think? Is this already included in the current designs?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 They are different as well, so you can close
