### ISSUE TITLE
Overview page not translateable

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#201]
**URL:** https://digitalstrategie-stage.liqd.net/admin/pages/35/edit/
**user:** admin
**expected behaviour:** I can adapt the page depending on the language
**behaviour:** I can only build one overview page in "common", but not in any other language. In the other languages, there are only general fields. Or did I get something wrong?
**important screensize:** desktop
**device & browser:** Firefox, MacOS BigSur
**Comment/Question:** Sorry, this must totally have slipped! Maybe we can change that as soon as we change the Styling, anyhow?

![Bildschirmfoto 2021-12-13 um 16 49 32](https://user-images.githubusercontent.com/30862422/145843752-01033d2e-1b22-416b-8da2-98cb618c7ca9.png)

![Bildschirmfoto 2021-12-13 um 16 49 56](https://user-images.githubusercontent.com/30862422/145843879-e6df7df3-2a25-4c3b-b03c-192fc8f94630.png)

**Comment by hmkay** [comment]
FYI @maxliqd

**Comment by fuzzylogic2000** [comment]
The translated info we use for the overview page is from the other pages. So, you add the blocks and the pages you want to put on there in common. And they are still translated because of the content of the linked pages.
Should we just talk about that? I think that is faster!

**Comment by fuzzylogic2000** [comment]
So, after talking, we found the problem and what to fix. We will:

- for the teaser blocks make the link text translatable and display all language fields in the teaserblocks in the common tabs
- @maxliqd will find out if we need the paragraph block and how (so, if (option 1) the intro text from the language tabs is enough, or if (option 2) it is enough to add teaser blocks at the end of the page and thus move that to the language tabs, or if (option 3) we need to add a special paragraph block with the translated fields in the common tab)
- decide how to proceed with the work for the paragraph blocks (option 1 and probably also 2 can be done in this issue, while 3 might be a small story)

**Comment by phillimorland** [comment]
@hmkay @maxliqd we need a desicion on how to solve this issue, we will definitely: 
- make the teaser link text a translatable field in the common tab
However we don't know what we should do about the paragraph block?
