### ISSUE TITLE
Search function: Display word(s) that have been searched

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#203]
**URL:** https://digitalstrategie-dev.liqd.net/search/?q=%C3%B6kologisch
**user:** participant
**expected behaviour:** I can see what I was searching for in case I forget it.
**behaviour:** There is no information / reminder on what I have searched

**Comment/Question:** Also maybe part of the restyling?

<img width="1405" alt="Bildschirmfoto 2021-12-15 um 16 21 33" src="https://user-images.githubusercontent.com/30862422/146214730-b5ddf010-3447-4dd6-951b-0f1f20bf0437.png">

**Comment by phillimorland** [comment]
I think this would also be covered in styling and so not part of the story but again useful reminder for when we do style it

**Comment by hmkay** [comment]
Thank you, @fuzzylogic2000 , is this story ok? Then we can close the issue!
https://taiga.liqd.net/project/liqd-liquid-software/us/5307?no-milestone=1
