### ISSUE TITLE
Search function: understanding why the results are being displayed

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#204]
**URL:** https://digitalstrategie-dev.liqd.net/search/?q=%C3%B6kologisch
**user:** participant

**Comment/Question:** I don´t quite know why the results which are being displayed are being displayed. So in this case, I searched for "ökologisch" and the landing page came out without any text. So I don´t quite understand why...?

<img width="1387" alt="Bildschirmfoto 2021-12-15 um 18 05 17" src="https://user-images.githubusercontent.com/30862422/146231724-91de2b36-8c63-44e1-a6ea-a2581143ff25.png">

**Comment by phillimorland** [comment]
@hmkay do you have the same issue from their search on their current site? the story was to implement their search on this site so it's only an issue if functionality is different, does that make sense?

**Comment by hmkay** [comment]
Yes, that makes sense, and yes, you are right - the page of them aslo does not have it. So I will turn it into a feature request!
