### ISSUE TITLE
Search function: Landing page does not show text

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#205]
**URL:** https://digitalstrategie-dev.liqd.net/search/?q=mehr
**user:** participant
**expected behaviour:** If I search for a word I expect to see the text field in which the word comes up.
**behaviour:** When searching "mehr" I get the landingpage, but no text field that has the word "mehr" in it.

**Comment/Question:** This was also not in the acceptance criteria, not sure if this is something that will also solve with styling? Also connected to #204 ?

![Bildschirmfoto 2021-12-16 um 10 54 24](https://user-images.githubusercontent.com/30862422/146349506-ce1f8a4d-84c9-44b5-bf21-ab02b8e0cdcc.png)

**Comment by phillimorland** [comment]
@hmkay is this not the same as 204?

**Comment by hmkay** [comment]
Nice! Yes, let´s keep this - or should I write a feature request / story out of it, @phillimorland ?

**Comment by phillimorland** [comment]
@hmkay this would be a feature request but I don't know how realistic it is as it's not our code (we just implemented elastic search) so I have no idea what is possible?! maybe @goapunk or @Rineee has more of an idea how adaptble elastic search is?

**Comment by goapunk** [comment]
The whole search backend is handled by Wagtail. I think there can be some improvements to how the results are shown, we also currently cut the text after 300 chars. And we most likely don't want the original styling (e.g. the yellow background, etc.) but just plain text (and e.g. the search term bold), like it's done on the main search at https://berlin.de

**Comment by fuzzylogic2000** [comment]
@hmkay @maxliqd I added "feature request" labels to all the search issues and assigned you. The story we did only included research and implementing the search. Brushing it up, styling, displaying the results and checking that is really does what we intended should be handled in the styling-story. So, could you add links to these three issues, but still close them? So, that we do not forget about it, but we also do not have issues cluttering our list that we cannot just do.

**Comment by hmkay** [comment]
It is all in this story now: https://taiga.liqd.net/project/liqd-liquid-software/us/5307?no-milestone=1
