### ISSUE TITLE
Footer alignment columns

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#233]
**URL:** https://digitalstrategie-dev.liqd.net
**user:** visitors
**expected behaviour:** Columns of two footers are aligned
**behaviour:** Columns are not aligned
**important screensize:** desktop
**device & browser:** safari, firefox
**Comment/Question:** 
Example for alignment: https://www.berlin.de/karriereportal/
It seems to be related to the responsive design, the number of columns and the ration of the browser window. 
Can you take a first look and see if you deem it problematic, @mcastro-lqd ?

![Bildschirmfoto 2022-02-07 um 17 31 20](https://user-images.githubusercontent.com/94360651/152830593-fad24029-ae95-4de8-bbad-915b9a7aa440.png)

**Comment by phillimorland** [comment]
not our code or bug, probably linked to https://github.com/liqd/digitalstrategie/issues/115

**Comment by phillimorland** [comment]
closed with impoted footer
