### ISSUE TITLE
Teaser version 2 Block does not cover the whole width of the tab

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#249]
**URL:** https://digitalstrategie-dev.liqd.net/über-den-prozess-overview-page/
**user:** visitor
**expected behaviour:** Box goes all the way to the sides
**behaviour:** Yellow box doesn't go all the way, there is a white space on the side, especially when you narrow the wind
**important screensize:**
**device & browser:** Macbook firefox and safari, iPhone safari
**Comment/Question:** 

Screenshot?

![grafik](https://user-images.githubusercontent.com/94360651/153824761-b27b7f17-28b6-4ed2-abf5-0e40d234ff8a.png)

**Comment by phillimorland** [comment]
This is from their css, there is a gap on the right on large screens and on the left on smaller screens >1030px comes from `    max-width: 99.2vw;` you can also see it on their page http://styleguide.berlin.de/patterns/09-vertical_marketing-page-modul-teaser-marketing/09-vertical_marketing-page-modul-teaser-marketing.html
We can overwrite it or request a fix, disadvantage of overwritting is if they do fix then our page may look a little off untill we update, @maxliqd @hmkay what do you think?

**Comment by hmkay** [comment]
Yes, we should leave them the fix, I´d suggest!

**Comment by phillimorland** [comment]
seems to be fixed https://gd-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
