### ISSUE TITLE
These slider long text not shown fully on full screen

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#252]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** Visitor
**expected behaviour:** These are shown completely.
**behaviour:** Not all text is shown. (Longer) Paragraph gets chopped off in the middle, appr. after 500 character.
**important screensize:** Full screen desktop
**device & browser:** Macbook, firefox, safari
**Comment/Question:** 
Introduce  character limitation?
Screenshot?
![grafik](https://user-images.githubusercontent.com/94360651/153874908-683d36ed-ab59-47e1-b3ed-aa442dc92873.png)

**Comment by hmkay** [comment]
@phillimorland yesss, sounds good!

**Comment by mcastro-lqd** [comment]
@phillimorland I agree, cause this module shouldn't be use in case of a longer text. I just checked the longer on on their website and it has 155chars, so 255 sounds more than enough. :)
