### ISSUE TITLE
Background white of module is not white as background of text

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#269]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** participant
**expected behaviour:** The white of the background of the modules is as white as the text?
**behaviour:** The white of the background of the modules appears greyish
**important screensize:** desktop
**device & browser:** macOS Monterey, Firefox
**Comment/Question:**  I am not sure if this is how it is meant to be - so confirmation from @mcastro-lqd needed =)

<img width="1080" alt="Bildschirmfoto 2022-02-15 um 17 23 20" src="https://user-images.githubusercontent.com/30862422/154104760-8957df3b-6dff-4bc8-8e96-d61695ba7e2d.png">

**Comment by hmkay** [comment]
not sure if you get the notification from the description, @mcastro-lqd , so here it comes in the comments as well to be sure!

**Comment by mcastro-lqd** [comment]
@hmkay Since we are using the "Version 2: Marketing Teaser (boxed)" it's up to us cause the colours can be on our choice as we are using them as if they were images. If we want a grey one, it should be #f7f7f7, if its a white one it should be #ffffff.

We haven't used any grey yet as far as I remember, but if you think it could be something in the future we can keep both

http://styleguide.berlin.de/patterns/09-vertical_marketing-page-modul-teaser-marketing/09-vertical_marketing-page-modul-teaser-marketing.html

**Comment by hmkay** [comment]
Yes, I was just wondering if the white background is the same white as the white background of the Test and picture? Now, it appears as if we have rather a grey background of the teaser, not white. Or did I get somthing wrong? @mcastro-lqd

**Comment by mcastro-lqd** [comment]
It appears to be that if we don't select any color, grey is shown, I'd rather change it to white and create a grey one if necessary or create a white one, it depends on what's easier for you @phillimorland 

<img width="1121" alt="Screenshot 2022-02-16 at 14 55 46" src="https://user-images.githubusercontent.com/59610786/154279126-f9911e4b-b501-4c60-ab68-15f4b494dc10.png">
<img width="1757" alt="Screenshot 2022-02-16 at 14 58 52" src="https://user-images.githubusercontent.com/59610786/154279667-da7c50e2-7690-4ce5-a6f0-b5058427444a.png">

**Comment by hmkay** [comment]
Yes, I also think we will not need a grey one, actually....

**Comment by mcastro-lqd** [comment]
@hmkay Yes, at least I couldn't find it on Zeplin, but Ive done so many screens that I don't know anymore

**Comment by phillimorland** [comment]
thats their default styling overwritting ours, i'll just overwrite theirs again, no worries!

**Comment by mcastro-lqd** [comment]
@phillimorland we can also leave it like that and add an white option if you don't want to change their default styling :)
