### ISSUE TITLE
#5406 Website shareable via social media, still linking to Datenschutz

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#276]
**URL:** https://digitalstrategie.berlin.de/haupt/de/gr%C3%BCnbuch/
**user:** Visitor
**expected behaviour:** When you share the link on social media, a correct preview is generated that does not link to the Datenschutzerklärung
**behaviour:** Preview relates to Datenschutzerklärung
**important screensize:**
**device & browser:** macbook, firefox
**Comment/Question:** 
Take a look here: https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdigitalstrategie.berlin.de%2Fhaupt%2Fde%2Fgr%25C3%25BCnbuch%2F

It does work for these sites though: 
- https://digitalstrategie.berlin.de/haupt/de/
- https://digitalstrategie.berlin.de/

Screenshot?
Issue:
<img width="410" alt="Bildschirmfoto 2022-02-21 um 11 57 49" src="https://user-images.githubusercontent.com/94360651/154943014-07dd6355-4d0e-45a4-96c4-c2f1b00431ab.png">

Good example:
<img width="418" alt="Bildschirmfoto 2022-02-21 um 11 59 08" src="https://user-images.githubusercontent.com/94360651/154943900-81522401-2e8b-4eca-ad82-22deea75a989.png">

**Comment by sabinammm** [comment]
@maxliqd at the risk of adding to the confusion, can you test whether you can edit the tags of these pages on stage and if that changes the description? My understanding was that once we deploy this version of stage to prod, it should also work for these.

**Comment by maxliqd** [comment]
@sabinammm 

It seems to work here: https://socialsharepreview.com/?url=https://ds-stage.liqd.net/haupt/de/gr%25C3%25BCnbuch/

<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/94360651/155113963-3fc479da-ea7f-4046-b553-afe29d0d274e.png">

But on Linkedin it does not yet:

<img width="456" alt="grafik" src="https://user-images.githubusercontent.com/94360651/155114300-a6814bfa-2cbb-46da-8674-17968b777da6.png">

**Comment by sabinammm** [comment]
No, it was still the same. I did the inspector thing to clean the cache. Then I had the new description. To test it yourself, you can create an article/post but never publish it.

**Comment by maxliqd** [comment]
@sabinammm Ok, linkedin still shows me the old preview in my chat messages, but that shouldn't be relevant for other users who haven't got old metatags in their cache, right?

**Comment by sabinammm** [comment]
Hmm, the cache is really linkedIn's cache, but maybe the user browsers also store these. This didn't happen for me. The message preview updated when the linkedIn-cache was cleaned via its post--inspector.

**Comment by maxliqd** [comment]
It got updated on my account without me doing anything within a day: 

<img width="399" alt="grafik" src="https://user-images.githubusercontent.com/94360651/155348474-4b519563-52b7-48f6-bc43-46fb3d2e125b.png">

**Comment by sabinammm** [comment]
This is in regard to the old site (US #5406) and was fixed here https://github.com/liqd/digitalstrategie-site/pull/12
