### ISSUE TITLE
Hero: White block underneath hero image

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#308]
**URL:** https://digitalstrategie-dev.liqd.net/
**expected behaviour:** In case of a purple theses slider, the hero smoothes into the slider as it is in the design
**behaviour:** There is a white block/line between theses slider and hero on the landing page (language: German), see screenshot
**device & browser:** Firefox, MacOS
**Comment/Question:** How do we deal with different blocks underneath the hero?

<img width="1005" alt="Bildschirmfoto 2022-03-22 um 14 22 26" src="https://user-images.githubusercontent.com/30862422/159491540-215f29ea-c937-49ec-bc93-e99296f4eb5b.png">

**Comment by phillimorland** [comment]
@hmkay what do you mean with 'deal with' ?
@khamui I can't replicate so appears to be a mac issue, can you take a look?

**Comment by hmkay** [comment]
@phillimorland the design only has the purple theses slider, which will be fine for the time being. I was just wodnerinig what would happen if e.g. the administration changes the first block (the theses slider)...I should just check/test it...

**Comment by phillimorland** [comment]
@hmkay yeah that's probably a good idea to test the different options!

**Comment by khamui** [comment]
@phillimorland yes it only appears between 1025px and 1370px. tested on safari and chrome

**Comment by phillimorland** [comment]
@khamui assigned you as cannot replicate on linux no matter size or browser (which is weird and bit worrying?! but meh)

**Comment by khamui** [comment]
okay will have a look. @hmkay no need for another issue, will check if its related.

**Comment by hmkay** [comment]
Ah, that is interesting! In the designs, there is no spacing, maybe we have an issue with the picture sizes here then? E.g.: When the picture is not big enough, it shows white spacing? @phillimorland

**Comment by phillimorland** [comment]
@hmkay i'm confused, this is the design right? https://app.zeplin.io/project/61cddb8e8de87f61376d8eef/screen/62176f523ab8945e416a385d
