### ISSUE TITLE
#5645 Hero title box spacing

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#310]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** Visitor
**expected behaviour:** The title box has consistent spacing like in the design: 30 px above, 34 px below subtitle
**behaviour:** Long subtitles lead to little space in the white box below, looks a bit crammed. No subtitle lead to a lot of space.
**important screensize:**
**device & browser:** mac firefox
**Comment/Question:** 

Screenshot

<img width="1409" alt="grafik" src="https://user-images.githubusercontent.com/94360651/159499383-1ca150a7-8c3b-4247-ae60-a17da61da7ff.png">

![grafik](https://user-images.githubusercontent.com/94360651/159499997-13986651-04ff-41d6-b8ca-dec762314c6c.png)

**Comment by phillimorland** [comment]
@maxliqd should we set the subtitle as required here? as I don't think making the box small will look very good as the heading will get lost in the image

**Comment by phillimorland** [comment]
![screenshot(26)](https://user-images.githubusercontent.com/5871230/159539989-76d1d289-b2f8-41e5-8ae8-23217d04922d.png)

**Comment by maxliqd** [comment]
@phillimorland: MK and I see your point. Could we make the subtitle mandatory? Wouldn't that prevent strange styling?

**Comment by phillimorland** [comment]
yep, sorry, 'required' means mandatory in code speak :p will set that

**Comment by fuzzylogic2000** [comment]
@sabinammm Can you please do this? Normally, (and for every other page), we would not set a default, but a one-of default. In this case, as we also want it to work with an empty DB, we probably have to set a default. Please try that out!
