### ISSUE TITLE
Module text with image: available on landingpage and detail page?

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#321]
**URL:** https://digitalstrategie-dev.liqd.net/ergebinsse/
**user:** admin
**expected behaviour:** I would like to add the text with image teaser also on other pages as only the landingpage
**behaviour:** I can only add it to the landing page

**Comment/Question:** The acceptance criteria claim we also wanted it on the detail pages. This is not yet possible, and I am also unsure: @maxliqd do you remember if we wanted them on the detail pages or overview pages? I feel they do not make sense on the detail pages...?

**Comment by hmkay** [comment]
So prio for adding would be:
1) Landing page
2) overview page
3) detail page. 

In he acceptance criteria, only the landing page and detail page were named. Soif i is too much work to add it everywhere, it would be only landing and overview!

**Comment by phillimorland** [comment]
@hmkay we can add it to overview page easily but it's not a teaser so not sure it makes sense?

**Comment by phillimorland** [comment]
@hmkay it's only because the overview page is meant to be a summary page and should link to other pages, and the text image block doesn't have a link so not sure why there would there be a none linking block on a page that should link to multiple other pages?

**Comment by hmkay** [comment]
@phillimorland that sounds totally reasonable and makes sense. Thank you for watching out for consistency!

**Comment by hmkay** [comment]
ah, no, this is the Text-Bild-Modul, @mcastro-lqd !
