### ISSUE TITLE
Teaser with columns: align text to 2 + 3 columns?

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#322]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** admin
**expected behaviour:** the two columns are aligned to another
**behaviour:** Due to different sizes of pictures and caption/copyright, the pictures are not aligned
**important screensize:** desktop, mobile
**device & browser:** MacOS, Firefox
**Comment/Question:** Can we somehow force it to be aligned or do we leave it to the admins to make it as nice as possible? What do you say, @khamui @phillimorland and @maxliqd ?

Screenshot?
<img width="1076" alt="Bildschirmfoto 2022-03-23 um 18 05 58" src="https://user-images.githubusercontent.com/30862422/159756039-6a9c6dda-5c7b-4c9b-bea8-44f3375c9738.png">

**Comment by hmkay** [comment]
And of course @mcastro-lqd , as soon as you are back ;)

**Comment by hmkay** [comment]
This also happens to the three columns: 

<img width="1129" alt="Bildschirmfoto 2022-03-23 um 19 35 27" src="https://user-images.githubusercontent.com/30862422/159771816-0337d96e-02a4-4b2a-a61e-3c352cc83055.png">

Should I do another issue or is it sufficient to have it here?

**Comment by phillimorland** [comment]
@hmkay we don't need another issue as it uses the same template
as for if we can force it, I would normally say yes but as we are using their css/html I'm not sure but I can have a poke and find out.
Can you test what happens if you add a really tall img?

**Comment by hmkay** [comment]
Hahahaha, yes, tested it on https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/ :

![Bildschirmfoto 2022-03-24 um 13 33 36](https://user-images.githubusercontent.com/30862422/159917082-5562b0f0-df11-4d29-94d3-ce409d87efdc.png)

**Comment by hmkay** [comment]
The picture on the right side is the really tall picture.

**Comment by phillimorland** [comment]
thank you!

**Comment by mcastro-lqd** [comment]
@phillimorland @hmkay we can use an Intrinsic aspect ratio of 4∶3
