### ISSUE TITLE
Detail page: Remember to get title in each language

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#324]
**URL:** https://digitalstrategie-dev.liqd.net/admin/pages/15/edit/#tab-common
**user:** admin
**expected behaviour:** I can set a title which appears in the breadcrums on the detail page for every page
**behaviour:** I can only set one title for the detail page which appears in the bread crum
**important screensize:**desktop, mobile

**Comment/Question:** I dunno if this needs an extra story, but there is this issue that the bread crums stay German for the detail pages. 

Screenshot?
<img width="683" alt="Bildschirmfoto 2022-03-23 um 18 22 40" src="https://user-images.githubusercontent.com/30862422/159758898-f709172a-d850-47f6-af3f-10b3159fe6d3.png">

**Comment by phillimorland** [comment]
@hmkay the breadcrumbs use the page titles which are used to generate the url, we wont use different urls for each language so i'm not even sure how we would go about this to be honest but yes it's definitely a story so will close this issue

**Comment by hmkay** [comment]
Ok, I added a story. It might be that we will have to work on that, let´s see.
