### ISSUE TITLE
Teaser Image: CTA button underneath text

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#325]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** participant/admin
**expected behaviour:** CTA is underneath text block
**behaviour:** With a small image, the CTA block is underneath the picture
**important screensize:** desktop, mobile
**device & browser:** MacOS, Firefox
**Comment/Question:** 

<img width="1108" alt="Bildschirmfoto 2022-03-23 um 18 30 22" src="https://user-images.githubusercontent.com/30862422/159761296-c4759f90-df5b-494b-bfd7-ae1802bdc059.png">

**Comment by phillimorland** [comment]
@hmkay should we implement a minimum size for these images? they don't actually look that good if they are small anyway?

**Comment by hmkay** [comment]
@phillimorland yes, that sounds good! Will there be a max size then, as well?

**Comment by phillimorland** [comment]
@hmkay what happens when you add a really big image?

**Comment by hmkay** [comment]
Againi, I used the very tall image, I hope that works, @phillimorland ? This is what happend:

![Bildschirmfoto 2022-03-24 um 13 37 28](https://user-images.githubusercontent.com/30862422/159918281-b26c62be-965a-450d-a69e-550492d9c488.png)
 
It is here, btw: https://digitalstrategie-dev.liqd.net/
