### ISSUE TITLE
mobile Overview page: picture in introduction

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#327]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** participant
**expected behaviour:** picture in text of the introduction adapts to screen size
**behaviour:** On mobile, the picture within the text of the introduction of an overview page does not scale (it appears).
**important screensize:** mobile
**device & browser:** iOS 15, Safari
**Comment/Question:** 

Screenshot?

![IMG_4AE89AF21B46-1](https://user-images.githubusercontent.com/30862422/159762886-0473bf3f-0971-4461-975f-063cb4dd125a.jpeg)

**Comment by phillimorland** [comment]
@hmkay can't replicate, can you check if it still does this after a re-fresh? because they use js not css for some of their responsive behaviour then changing the size of the screen without a refresh means some of their styling doesn't get implemented.

**Comment by hmkay** [comment]
I think i was hard, because of the kind of picture. I exchanged the picture and on mobile, it now looks squeezed in...here is the screenshot:

![IMG_34E67A673345-1](https://user-images.githubusercontent.com/30862422/159915284-22b4eb68-661b-4b66-bb63-92f1706aaa4e.jpeg)

**Comment by hmkay** [comment]
Ah, and I forgot to mention you, @phillimorland

**Comment by phillimorland** [comment]
@hmkay I still can't replicate even on a mac or my mobile, are you testing with responsive mode or on your actual mobile?

**Comment by hmkay** [comment]
I now put the same picture underneath each other so you can see the difference better: https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/

**Comment by hmkay** [comment]
![Bildschirmfoto 2022-03-24 um 13 48 01](https://user-images.githubusercontent.com/30862422/159919558-ccd314bf-4843-4ba1-bc7b-d8a156334e81.png)

**Comment by phillimorland** [comment]
@hmkay thanks for comparison but unless I can test it locally I can't really fix it @khamui can you see if you can replicate? my mac is running an older OS so maybe that's why I cant replicate

**Comment by khamui** [comment]
so i was able to replicate the issue on my mac in chrome.
@hmkay it would be a little bit of work to make richtext images format right. If this is not super important (for now) we could remove the feature, because above the introtext we have the mandatory header image anyways. What do you think?

**Comment by hmkay** [comment]
Yes, that might be a nice idea! Even though I am torn - if it isn´t an issue on most devices, maybe it is also ok to leave it like that...? What do you think, @khamui ?

**Comment by khamui** [comment]
i think it depends on if we expect intro texts to contain images or not. If we know already that it will be mostly a header and the text (only) i think we can leave it for now. Do we know this beforehand, @hmkay ?

**Comment by khamui** [comment]
yes, i see your point. That leads to me thinking, that we should try to have a proper solution for richtext embedded images :) I will try to come up with a solution @hmkay.

**Comment by hmkay** [comment]
nice, thanks @khamui ! =)
