### ISSUE TITLE
#5650 Teaser Tiles tall images effect format

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#336]
**URL:** https://digitalstrategie-dev.liqd.net/ergebinsse/
**user:** visitor
**expected behaviour:** Tiles always have the same ratio, regardless of inserted image
**behaviour:** Tiles have portrait ration when you insert one tall image
**important screensize:**
**device & browser:** Mac, firefox, iphone firefox
**Comment/Question:** 
Do we need to shrink the image? Or is no one likely to insert an image like that?

Screenshot?
<img width="340" alt="grafik" src="https://user-images.githubusercontent.com/94360651/159931946-3a04fb38-6c33-4b94-9a33-2eb56cf183d4.png">

<img width="329" alt="grafik" src="https://user-images.githubusercontent.com/94360651/159932109-5f925753-c527-477f-ae9d-0b77cf2887d5.png">

**Comment by phillimorland** [comment]
duplicate
