### ISSUE TITLE
Teaser tiles can should only link to Grünbuch detail pages

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#338]
**URL:** https://digitalstrategie-dev.liqd.net/ergebinsse/gr%C3%BCnbuch-overview-page/ 
**AND**: https://digitalstrategie-dev.liqd.net/ergebinsse/
**user:** admin
**expected behaviour:** The acceptance criteria state that the teaser tiles should only lead to detail pages of the Grünbuch. 
**behaviour:** I can link any page to the teaser tiles.
**important screensize:** desktop, mobile
**device & browser:** MacOS, Firefox
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@sabinammm We can restrict the page types to choose in a PageChooserBlock by the page_type attribute: https://docs.wagtail.org/en/stable/reference/streamfield/blocks.html#wagtail.core.blocks.PageChooserBlock
