### ISSUE TITLE
Landing page: A lot of padding between Theses slider and FAQ

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#339]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** participant
**expected behaviour:** The modules are closer together 
**behaviour:** the end of the theses and the title of the FAQ module appear to be far away from another (note: I am not an UI/UX expert! ;) )
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

![Bildschirmfoto 2022-03-24 um 15 41 05](https://user-images.githubusercontent.com/30862422/159941895-6129cf01-f20b-4016-9668-f4981faa2316.png)

**Comment by fuzzylogic2000** [comment]
So, do we have decision here? It should be smaller? I guess it is also smaller in the designs?

**Comment by hmkay** [comment]
uh, I dunno - maybe check with @khamui ? I am also not sure which should be smaller: If the theses slider should adapt it´s size depending on the amount of text?

**Comment by mcastro-lqd** [comment]
@hmkay @khamui I would first see if its possible to make the height adjustable depending on the Text. 

Also there won't be this slider + FAQ on the same page as far as I know. I would rather comment on the final thing done than on Templates like that, cause the content might be super different in the end. In this case specifically it does look too much spacing.

**Comment by fuzzylogic2000** [comment]
@hmkay @mcastro-lqd So, we close this for now and check with the "real" content later, right?
Or should we get rid of some padding for example for the FAQs? I think it would look weird if the slider would jump in height while sliding through it.

**Comment by khamui** [comment]
note to the FAQ spacing: it is already reduced (the picture above is not the current state).

**Comment by hmkay** [comment]
Let´s close and check later! Thank you, @khamui and @fuzzylogic2000 !
