### ISSUE TITLE
YouTube: DSGVO conform embed

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#342]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** participant
**expected behaviour:** I would like to be asked if YouTube is allowed to collect my data.
**behaviour:** YouTube just plays the video without me accepting their data protection

**Comment/Question:** Unsure, if we need the videos at all but either we should disable them in rich text or include a DSGVO conform way to do that.

Screenshot?

![Bildschirmfoto 2022-03-24 um 15 55 00](https://user-images.githubusercontent.com/30862422/159945664-86104394-2ed4-41b3-88c7-59edec696557.png)

**Comment by phillimorland** [comment]
@hmkay adding the dsgvo would be a story so we are better off just disabling video, that good for you?

**Comment by hmkay** [comment]
Yes!

**Comment by phillimorland** [comment]
@hmkay as this will mean editing the richtext interface, is there anything else we should remove? like adding images to the faq for example?

**Comment by hmkay** [comment]
I would leave it like that for now - I cannot think of anything else. The picture are good to have there!
