### ISSUE TITLE
#5698 Char limit in title FAQ module

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#359]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** cms-editors/
**expected behaviour:** Char limit caps the length of title.
**behaviour:** FAQ does not seem to have a char limit, thus the title can get super long
**important screensize:**
**device & browser:** Mac firefox
**Comment/Question:**
@hmkay Should we set a limit of 130 here as well? Or do we need characters here?
Screenshot?

<img width="742" alt="grafik" src="https://user-images.githubusercontent.com/94360651/160814403-2e2527dc-5240-4788-ae98-a7298c155327.png">

**Comment by hmkay** [comment]
Sounds good, @maxliqd !
