### ISSUE TITLE
#5648 position external link icon teaser colums

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#360]
**URL:** https://digitalstrategie-dev.liqd.net/common-title-gr%C3%BCnbuch-overview-page/
**user:** visitor
**expected behaviour:** External link icon is on some height/ in line with text
**behaviour:** External link icon is positioned a little higher
**important screensize:**
**device & browser:** Mac firefox, chrome, iphone 11 firefox
**Comment/Question:** 

Screenshot?

<img width="974" alt="grafik" src="https://user-images.githubusercontent.com/94360651/160845734-49639aa4-af64-4764-bcf5-b778d1acbfe4.png">

**Comment by fuzzylogic2000** [comment]
@maxliqd I agree, it looks better in the designs. But I don't think, we should use time on changing it, when it is like in the official styles now. 
Can we close it? Should we work on it? Someone has to decide! @hmkay ? :smile:

**Comment by hmkay** [comment]
I am totally fine with closing it, but as @mcastro-lqd is the expert on Design, he gets the final say ;D

**Comment by phillimorland** [comment]
We should stick with their link button, otherwise we will have to write our own which if they change their styles ours will be out of date
