### ISSUE TITLE
#5650 teaser tiles spacing under headline

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#364]
**URL:** https://digitalstrategie-dev.liqd.net/common-title-gr%C3%BCnbuch-overview-page/
**user:** visitor
**expected behaviour:**  More space between headline teaser tiles and tiles 
**behaviour:** Spacing looks smaller.
**important screensize:**
**device & browser:** Mac firefox, chrome, iphone firefox
**Comment/Question:** 
@mcastro-lqd It looks less problematic on mobile to me, compared to this design: https://app.zeplin.io/project/61cddb8e8de87f61376d8eef/screen/61d716f35c32ec7949a4d804
It doesn't necessarily show the headline.
Screenshot?

<img width="677" alt="grafik" src="https://user-images.githubusercontent.com/94360651/160878703-d7f4b0fc-feee-4c75-86ba-0b8681fcecf7.png">

Mobile
<img width="510" alt="grafik" src="https://user-images.githubusercontent.com/94360651/160878543-68cffe59-ba76-482e-ba5b-34fcf6cef59e.png">

**Comment by fuzzylogic2000** [comment]
@khamui Can you check that we use the proper classes from their styleguide? If we do, I think it should stay like this. :woman_shrugging:

**Comment by khamui** [comment]
indeed we miss a class there, but it won't affect the bottom margin, but the top margin. spacing between h2 and the tiles seems to be correct (if styleguide is "correct"). The missing class will come together in an upcoming PR
