### ISSUE TITLE
#5717 Metatags not setable for overview pages

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#369]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** cms-editor
**expected behaviour:** You can set metatags in the cms to generate beautiiiiful social media previews
**behaviour:** Possible for landing page, but neither overview, detail, grünbuch index nor grünbuch detail.
**important screensize:**
**device & browser:** Mac firefox
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Decision:

- [ ] we will add the meta tags to the overview and GruenbuchOverview pages
- [ ] we will test if it is easy to find out if the title is filled in and if yes, check for that additionally to the description

**Comment by fuzzylogic2000** [comment]
@hmkay We actually already spent too much time on it. But now it is really cool and can be used in other projects as well. :)

**Comment by hmkay** [comment]
Haha, ok ;)
