### ISSUE TITLE
do we use font awesome (and if yes is it still working?)

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/digitalstrategie#372]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** I just noticed that we already updated font awesome to v6. As that broke the icons on other platforms and I saw earlier, that we do not use font aweseome directly, but only via the berlin.de styles, I was wondering 
1. do we use font awesome and if not, can we remove the dependency
2. if we use it, are the icons broken?

@khamui Could you have a look?

Screenshot?

**Comment by goapunk** [comment]
I think it probably got upgraded by mistake. We should add add a renovate thing to keep it < 6

**Comment by phillimorland** [comment]
@khamui we installed it before we had their CI and styleguide so it's just a relic
