### ISSUE TITLE
caption not shown under images of blocks "teaser image" and "text mit bild"

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#379]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** visitor
**expected behaviour:** Caption gets shown under images of block
**behaviour:** only copyright visible
**important screensize:**
**device & browser:** Mac firefox, chrome
**Comment/Question:** 

Screenshot?

**Comment by sabinammm** [comment]
@maxliqd the styleguide shows their "Marketing Teaser (imageteaser)" with only copyright (even in the code underneath the example). I'm uncertain which one exactly corresponds to which type of block that we use. There is also their "Multiteaser", which we only use on the overview pages, as far as I understand, but call teaser columns (e.g. [here](https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/).

**Comment by maxliqd** [comment]
@sabinammm The "Marketing Teaser (imageteaser)" is our "teaser image". Our block "text mit bild" is their "Text-Bild-Modul 50 %". The latter has a caption in the styleguide. But regarding our "teaser image": Hmmmm, it seems incoherent to me. All other examples of teasers with images have captions in the styleguide. Maybe a mistake in the styleguide=
@hmkay: I would say add the caption to all images, do you agree?

**Comment by maxliqd** [comment]
@sabinammm Just talked to @hmkay: she wants to stick to the styleguide, so no caption under teaser image.

**Comment by sabinammm** [comment]
@maxliqd thank you for clearing it up :)

**Comment by phillimorland** [comment]
@hmkay @maxliqd in the code examples, image captions are not shown on either teasers or text-bild modules but in the example pages they are so will add them like they are in example pages

**Comment by maxliqd** [comment]
@phillimorland @hmkay Ok, you can add the caption to both blocks. Thx a lot!
