### ISSUE TITLE
Content Block CTA, link mandatory for button

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#382]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** cms-editor
**expected behaviour:** all CTA blocks have a button, currently cms editors can leave them out.
**behaviour:** not mandatory to insert link, therefore it is possible to have CTA blocks without buttons
**important screensize:**
**device & browser:** Mac firefox
**Comment/Question:** 
Not necessary for the launch, but for when we hand it over, I guess.
Screenshot?
![grafik](https://user-images.githubusercontent.com/94360651/161579053-8a4b7b77-86ce-4eeb-9cca-2daa30b59faa.png)

**Comment by fuzzylogic2000** [comment]
Block will be removed
