### ISSUE TITLE
#5645 Landing Page: Actual Hero

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#387]
**URL:** https://digitalstrategie-dev.liqd.net/
**important screensize:** *Both*
**device & browser:** *Safari Version 15.3 (17612.4.9.1.8)*
**Comment/Question:** *If possible, I’d also reduce the spacing a bit between the title and the paragraph. Also, in order to show the full illustration, would it still be possible to add the parallax scrolling effect here? I can provide the image with enough height.
Thanks!*

<img width="1792" alt="Screenshot 2022-04-05 at 17 38 18" src="https://user-images.githubusercontent.com/59610786/161791882-9033505c-0ef4-46df-976e-e6cba4973059.png">

**Comment by phillimorland** [comment]
Damm we forgot about the scrolling when doing the story, I think we need to add these things to the stories as we can't always tell from the design/don't look at them will add this to the handover milestone
