### ISSUE TITLE
#5649 Create Content Block with image and colourful background

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#388]
**URL:** https://digitalstrategie-dev.liqd.net/
**important screensize:** *Mobile*
**device & browser:** *Safari Version 15.3 (17612.4.9.1.8)*
**Comment/Question:** *Can we use the same spacing from the sides on top of the image? I think it would look more balanced.
Thanks!
![imageandcolor](https://user-images.githubusercontent.com/59610786/161792398-a270221e-5177-4909-b335-39d4bc6eb0d5.jpg)
*

**Comment by fuzzylogic2000** [comment]
@maxliqd This issue is pretty old, is this still a problem after our restylings? And should we change it like that even though we probably use the styles from the styleguide?

**Comment by fuzzylogic2000** [comment]
Yes, I checked it, it's still a problem. I have no idea where it comes from, though. Could you maybe have a look @phillimorland ?

**Comment by phillimorland** [comment]
@fuzzylogic2000 @mcastro-lqd can you send a link as I can't find an example?! only place similar is this and that styling is due to breadcrumbs  https://gd-dev.liqd.net/en/gr%C3%BCnbuch-overview-page/
![screenshot(35)](https://user-images.githubusercontent.com/5871230/200251381-3e65cb16-6e04-48cb-89c4-51cad69bc6a9.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland It's on the German landing page: https://gd-dev.liqd.net/de/
![Screenshot from 2022-11-07 08-41-55](https://user-images.githubusercontent.com/8178179/200253368-c60ff6a6-249d-42e2-ab1e-5e279450cc3b.png)

**Comment by mcastro-lqd** [comment]
@phillimorland do you understand now what Katharina meant?
