### ISSUE TITLE
FAQ Block Spacing

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#390]
**URL:** https://digitalstrategie-dev.liqd.net
**important screensize:** *Both*
**device & browser:** *Safari Version 15.3 (17612.4.9.1.8)*
**Comment/Question:** *The spacing between questions and answers are a bit off. The spacing between the question and Answer's paragraph should be smaller than the spacing between the main title and the question.*
![Screenshot-2022-04-05-at-15 57 05](https://user-images.githubusercontent.com/59610786/161793821-bdb83bc9-4cdf-4e82-a3e3-34125d811317.jpg)

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd The different spasing is still the case:
![Screenshot from 2022-11-04 11-47-05](https://user-images.githubusercontent.com/8178179/199954871-a8f05db3-2471-474c-881a-4d1e5d4e1507.png)

But it's all from the Berlin-styles. So should we change it? We could overwrite the styles to have a smaller padding like this:
![Screenshot from 2022-11-04 11-49-38](https://user-images.githubusercontent.com/8178179/199955260-f443842d-1ebb-46a0-92a6-d3276235c90b.png)
(Just removed the padding from the `js-accordion__panel`)

Or should it be even less? Then we need to make sure, that we only remove the padding on the open question.

**Comment by fuzzylogic2000** [comment]
We need decision! @mcastro-lqd or @maxliqd

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 If its from their Style, then maybe not? Or just if the GD people complain, then I would inform Landesredaktion, cause they are the ones responsible for it too.

**Comment by maxliqd** [comment]
@fuzzylogic2000 @mcastro-lqd Let's not overwrite it. The block will not be used on landing or overview pages, so not high prio.
