### ISSUE TITLE
teaser with image char limit body

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#395]
**URL:** https://digitalstrategie-stage.liqd.net/
**user:** cms editor
**expected behaviour:** I can fill in as much text as would fit next to the image
**behaviour:** Characters limited to 300, only half of the space next to the image is filled with headline, body and button
**important screensize:**Desktob
**device & browser:** Mac firefox
**Comment/Question:** 
When you zoom in the font gets bigger. But I can zoom in a lot until the button moves under picture. See second screenshot.
Would we have to play around a bit with the char limit? Maybe try 500 or 600?

Screenshot?
No zoom:
![grafik](https://user-images.githubusercontent.com/94360651/162407178-f21c90d4-7e60-4add-adfc-d13dffd50a28.png)

A lot of zoom -- until the button is under the image:

![grafik](https://user-images.githubusercontent.com/94360651/162407997-34dbe25a-0470-4f9d-99ee-40b0f1b3d444.png)

**Comment by phillimorland** [comment]
@maxliqd so to confirm we should increase the char count to 500 and the zoom has nothing to do with anything right? unless we have to do something about the zoom?

**Comment by maxliqd** [comment]
@phillimorland 

When you zoom in a lot, the text grows faster than the image. Thats why you get to this overflow. I think it is a bit of a trade-off: If we want to be super sure that the CTA stays next to the image, we have to keep the char limit lower. But I don't think a lot of users will zoom in frenetically.

Thus, I am not one hundred percent sure about the exact number, but I would suggest we try to fit in as much as possible next to the image?  The upper block has 700 characters in the body. Would that work?

I don't thin you need to change much about the zooming, I am assuming that would be a lot more work. For me a higher char limit would be totally ok. Hope this helps. 

![grafik](https://user-images.githubusercontent.com/94360651/165125655-c1262738-4eb2-4eb0-85c8-523450a4670d.png)

**Comment by fuzzylogic2000** [comment]
@maxliqd We just need a decision here. So, we should increase it to 700, 600 or 500?
