### ISSUE TITLE
Spacing burger menu  

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#402]
**URL:** https://digitalstrategie-stage.liqd.net/%C3%BCber-den-prozess/
**user:** visitor
**expected behaviour:** spacing between languages as big as between other menu items
**behaviour:** more space between languages
**important screensize:** desktop, mobile
**device & browser:** Mac firefox, iphone safari
**Comment/Question:** 

Screenshot?

![grafik](https://user-images.githubusercontent.com/94360651/164043345-f4215ddb-9ba3-4ec6-a7eb-e5f660ee278a.png)

**Comment by phillimorland** [comment]
check if this is a styling import, maybe bootstrap?
