### ISSUE TITLE
 Menu items indicate which overview page I am on by turning bold und unfolding

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#404]
**URL:** https://digitalstrategie-stage.liqd.net/
**user:** visitor
**expected behaviour:** When I am on an overview page, which has a menu item, and I open the burger menu the respective  sub items are shown below. In the main menu, the item of the page I am on is bold
**behaviour:**  Main menu items are not all bold (Über den Prozess is not, Ergebnisse is bold), burger sub items not unfolded
**important screensize:** desktop, mobile
**device & browser:** mac firefox, iphone safari
**Comment/Question:** 

example: [https://www.berlin.de/corona/massnahmen/verordnung/bussgeldkatalog/](https://www.berlin.de/corona/massnahmen/verordnung/bussgeldkatalog/)

Screenshot?
![grafik](https://user-images.githubusercontent.com/94360651/164046262-dc1938da-e242-4d62-b7d7-7a317eb365b6.png)

How it could look like:

![grafik](https://user-images.githubusercontent.com/94360651/164046859-3b01d78c-b747-43b9-a536-db2893b7dcfb.png)

**Comment by phillimorland** [comment]
@maxliqd @hmkay is this still an issue?

**Comment by hmkay** [comment]
I think it is done - I don´t see an issue anymore, but will leave final say to @maxliqd =)
