### ISSUE TITLE
Intro image width on mobile

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#405]
**URL:** https://digitalstrategie-stage.liqd.net/%C3%BCber-den-prozess/
**user:** visitor
**expected behaviour:** intro image covers the full width 
**behaviour:** intro image does not cover the full width
**important screensize:** mobile
**device & browser:** iphone 11 firefox
**Comment/Question:** 

Related to CSS of LR, solution soon to be published in styleguide

Screenshot?

Mobile 
![grafik](https://user-images.githubusercontent.com/94360651/164230519-03421afe-227a-411a-aece-7e953caf083e.png)

**Comment by phillimorland** [comment]
@maxliqd margins have been reduced but are not gone, should we overwrite their css to achieve this? https://gd-dev.liqd.net/%C3%BCber-den-prozess-overview-page/

**Comment by maxliqd** [comment]
@phillimorland I don't think so. The teaser image block with coloured background is also affected, as would be the images in rich text blocks. They have margins too.
