### ISSUE TITLE
Upcoming CSS updates for search form and buttons

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#406]
**URL:** https://digitalstrategie-stage.liqd.net/
**user:** visitor
**expected behaviour:** styling stays nice
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:**

Information provided by LR: 
Styleguide: Search forms styling will be updated end of April, buttons probably mid-May. 

Depending on how the CSS is integrated, the website could get the updated stylings from the live CSS. Styleguide is no versioning yet. Therefore, it may be advisable to provide the CSS oneself until there is a versioning.

Screenshot?

**Comment by phillimorland** [comment]
this is dealt with fixed https://github.com/liqd/digitalstrategie/pull/531
