### ISSUE TITLE
New class name Icontile to be introduced for teaser tiles

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#407]
**URL:** https://digitalstrategie-stage.liqd.net/gr%C3%BCnbuch/
**user:** dev
**expected behaviour:** class names are up to date
**behaviour:** as new class name specifically made for teaser tiles will be introduced in update of styleguide  (20 April),  class name will not correspont to styleguide anymore
**important screensize:**
**device & browser:** 
**Comment/Question:** 
LR advises to then use new class name Icontile instead of Teasertile, which is now in use.

Screenshot?

**Comment by fuzzylogic2000** [comment]
Hmm, I guess that should have been in a story to properly test it? Are you sure, you want to do that directly before the release? But we can of course do it if we need to.

**Comment by maxliqd** [comment]
@fuzzylogic2000 For me it is a nice to have, so let's remove it from the milestone.

**Comment by phillimorland** [comment]
@maxliqd also just a heads up, their new tiles are a different design to ours so they would look different, not sure if we want that at all?
![screenshot1](https://user-images.githubusercontent.com/5871230/200865913-eec328d6-e542-4231-b049-12374b616b37.png)
![screenshot(36)](https://user-images.githubusercontent.com/5871230/200865926-86b3e2a9-d16b-4019-818c-b0792a3655f6.png)

**Comment by maxliqd** [comment]
@phillimorland We want to stick to our design. They created a new classname for them: 
![image](https://user-images.githubusercontent.com/94360651/200868509-682a0fed-bdce-4c05-b5cc-59e15cc9105c.png)
