### ISSUE TITLE
Burger menu styling safariOS

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#408]
**URL:** 
**user:** 
**expected behaviour:** coherent styling across browsers, especially on safariOS too
**behaviour:** burge menu styling gets overwritten, chevron is blue
**important screensize:**
**device & browser:** SafariOS
**Comment/Question:** 
LR will take care of debugging medium-term and release in styleguide
Screenshot?

**Comment by fuzzylogic2000** [comment]
If it will be taken care of, we will get it automatically. So, will close this!
