### ISSUE TITLE
Font awesome not loading correctly

### ISSUE THREAD

**Issue by phillimorland** [liqd/digitalstrategie#411]
Add berlin.de to allowed resources in admin
`downloadable font: download failed (font-family: "Font Awesome 5 Free" style:normal weight:900 stretch:100 src index:3): bad URI or cross-site access not allowed source: https://www.berlin.de/i9f/r1/webfonts/fa-solid-900.ttf`
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.berlin.de/i9f/r1/webfonts/fa-solid-900.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

**Comment by fuzzylogic2000** [comment]
Is this still a problem? If yes, @goapunk could you have a look?

**Comment by goapunk** [comment]
Apparently not, I don't really get why though, we didn't change anything, did we @phillimorland ?

**Comment by phillimorland** [comment]
nope but as we load their styles I think we should still add berlin.de as an allowed resource, browsers are getting stricter so would be nice to not have to worry

**Comment by goapunk** [comment]
@phillimorland not sure, `Access-Control-Allow-Origin` is something they would have to set in their server, not us on our afaik. We can only set csps allowing the browser to load from their site.

**Comment by phillimorland** [comment]
@goapunk so we close?

**Comment by goapunk** [comment]
@phillimorland close or rename/repurpose to "Add CSPs (e.g. berlin.de)" ?
