### ISSUE TITLE
Block Paragraph background colour

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#424]
**URL:**  example: https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** CMS editor
**expected behaviour:** paragraph blocks are always white and I cannot accidentally choose colours
**behaviour:** Colours can be chosen
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

<img width="1038" alt="grafik" src="https://user-images.githubusercontent.com/94360651/166663007-964947b7-3426-4a2d-b86d-4b5880f7a8a6.png">

**Comment by fuzzylogic2000** [comment]
So, this issue means, that we should remove the background colour for the paragraph block? (That will apply to that block on all pages.)

**Comment by maxliqd** [comment]
Yes, please remove the colour. The styleguide does not allow for background colours in blocks which we don't want to highlight (like the teasers). Thank you!
