### ISSUE TITLE
Images in rich text of block paragraph: no caption, no copyright field

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#425]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** CMS editor
**expected behaviour:**  I can add a caption and copyright to all images.
**behaviour:** I can do so for blocks like text with image and teasers, but not in the rich text of the block paragraph.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

I don't think this was ever an acceptance criteria in any story. Thus: maybe not an issue, rather a new story?

Screenshot?

**Comment by fuzzylogic2000** [comment]
Yes, we can do that: https://docs.wagtail.org/en/stable/advanced_topics/images/changing_rich_text_representation.html
And yes, that would be a story.

**Comment by maxliqd** [comment]
@hmkay I don't think this is necessary right now. We can add caption and copyright manually. It would only become relevant for the handover.
