### ISSUE TITLE
Teaser image spacing between image and caption

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#427]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** Visitor
**expected behaviour:** Spacing is just as big as spacing in other blocks with images
**behaviour:** Very little space on mobile
**important screensize:**Mobile
**device & browser:** iphone safari
**Comment/Question:** 
@mcastro-lqd Can you double check this?
Screenshot?

![grafik](https://user-images.githubusercontent.com/94360651/166681587-52b6d4d1-e3bf-4155-ab16-c60188e6dbcf.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland Also the block you are working on? :woman_shrugging:

**Comment by phillimorland** [comment]
not right now

**Comment by phillimorland** [comment]
column teaser issues https://gd-dev.liqd.net/%C3%BCber-den-prozess-overview-page/

**Comment by maxliqd** [comment]
We don't use the block with the caption or copyright at the moment. I don't see the practical necessity to fix this.
