### ISSUE TITLE
Teaser colums external and internal link choosable

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#428]
**URL:** https://digitalstrategie-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** CMS editor
**expected behaviour:** I can only insert one link: Internal or external
**behaviour:** I can do both and they show on the website.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Seems like low prio to me.

Screenshot?

![grafik](https://user-images.githubusercontent.com/94360651/166681952-8a6858da-cae0-42bd-bc8f-ea8e1b545c9a.png)

**Comment by fuzzylogic2000** [comment]
What should we do?

1. (Try and) make the form only allow to fill in one field?
2. Or only display one of the links when both are set? (And if yes, which one? Should the internal one take precedence?)
3. Or keep both links and leave the block like that? (close the issue)

**Comment by maxliqd** [comment]
Ok cool, so number 2. Let the internal one take precedence. At least we know where we are taking the user in that case. Thank you!
