### ISSUE TITLE
Newsletter: indication of required field

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#457]
**URL:** https://gd-dev.liqd.net/
**user:** participant
**expected behaviour:** required tick in check box is indicated and accessible
**behaviour:** There is a star saying "erforderlich".
**important screensize:** desktop and mobile

**Comment/Question:** Wasn´t the star less accessible? We could also just leave it and only show the error, I suppose. That is according to the style guide, right?

Screenshot?
<img width="981" alt="Bildschirmfoto 2022-05-18 um 17 00 11" src="https://user-images.githubusercontent.com/30862422/169073867-00aa6aa2-394e-4408-bea5-f43d22db16a4.png">

**Comment by phillimorland** [comment]
@hmkay so the sentence is written by you so you can add the star there, is that what you mean? 
This was done according to the design that we were given, the styleguide use a slightly different design to the one we use for all our forms, here is design we followed: https://app.zeplin.io/project/61cddb8e8de87f61376d8eef/screen/62176f523ab8945e416a385d

**Comment by hmkay** [comment]
Well my question was rather regarding a11y:
Because what I got is that the start is less accessible because it is being read out. I was wondering if we could simply not put it - that would be the word ***Erforderlich** because I think I cannot change that, right?

**Comment by phillimorland** [comment]
@hmkay no you can't change it however as it's not a form label it's not read out by tabbing through the form anyway, it's only read out when reading the page, which is different to tabbing. Also if we change it here we should change it on all our forms. 

I do have a question about deadlines, as non of the forms will be included in the soft launch page, should this issue be in the milestone?

**Comment by hmkay** [comment]
@phillimorland ok, then this is probably a bigger discussion on the forms and at the same time probably not too relevant, so I will close the issue.

Regarding the deadlines: Yes, I am myself quite often unsure which of the issues should go where. E.g. in this case, it was about the newsletter block which was a story of last sprint. It won´t be there on the launch, but maybe the newsletter will come rather soon after it. So in this case it wold be: It is not needed now now, but I don´t know if we will have another release before we will need it.
