### ISSUE TITLE
Wagtail overview page: Preview does not show modules

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#458]
**URL:** https://gd-dev.liqd.net/admin/pages/23/edit/preview/ vs. https://gd-dev.liqd.net/%C3%BCber-den-prozess-overview-page/
**user:** admin
**expected behaviour:** When clicking on "preview" in wagtail, I am shown the potential website.
**behaviour:** Preview does not include the modules.
**important screensize:** desktop
**device & browser:** Firefox, MacOS
**Comment/Question:**

**Comment by phillimorland** [comment]
@hmkay ok i see a bunch of modules on ff linux?! do you just see a blank page when viewing preview? can you add a screen shot? als have you tried other browsers? and what addons or extensions are you using that may cause issues?

**Comment by phillimorland** [comment]
@hmkay but you added it to the softlauch milstone?!

**Comment by phillimorland** [comment]
@hmkay also for some reason you are seeing the english version when you preview and the german version when you view live, have you tried swapping the language?

**Comment by hmkay** [comment]
I was wondering about that - if I just did something wrong, but couldn´t point my finger to it! So sorry. Thank you for checking. Will close issue.

Regarding the prio: Yes, I added it to the milestone. Sometimes I am confused where to put it and I thought if it was easy to fix, that would be fine - and if it was harder I´d remove the milestone. I thought the milestone is something like our discussion, where you try to get issues out of the milestone and PMs trying to get some in there :D

And for the prio I thought we had different lables? Sorry if I added to the confusion!

**Comment by phillimorland** [comment]
@hmkay good point about confusion on milestones and labels, I would say for release milestones it's best to only have things in the milestone that need to be there for the release, particularly as this is a external deadline release. The other issues can be prioritised with labels and if we have time before release we can look at those ones but if we are on a tight schedule it's nice to absolutely know what needs doing. Like with everything though it is on a case by case basis so there's no definite right way, we're so 'agile' ;)

**Comment by hmkay** [comment]
😆 Thank you for the explanation and also for the patience =)
