### ISSUE TITLE
Kontaktformular German button in English

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#462]
**URL:** https://gd-dev.liqd.net/kontakt/
**user:** visitor
**expected behaviour:** Once you have submitted your message, the button to go back to website is English
**behaviour:** Should be German "Zurück zur Startseite"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

![image](https://user-images.githubusercontent.com/94360651/169235587-98074bf1-e3ce-4a52-95c6-aaa5d1582630.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 have you any clue?

**Comment by phillimorland** [comment]
@hmkay again will we include this form in the initial launch? I realise its definitely a problem but knowing if it will be included will decide the resources we allocate

**Comment by maxliqd** [comment]
@phillimorland We're currently planning to include it, but we are still walking on very shaky planning grounds...
