### ISSUE TITLE
Headlines FAQ: H2 and H3 can be mixed

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#463]
**URL:** https://gd-dev.liqd.net/faq/
**user:** participant
**expected behaviour:** As LIQD we want to make sure that the headline levels are in the right order, in order to be accessible.
**behaviour:** The content of the FAQ can have an H2 again, which seems to break the logic of the headlines going rather down.

**Comment/Question:** I don´t know how important this is, neither do I know if this is something we can solve technically. We do need the rich text for picture, so there are the H2 and H3. Also, I think this should be the literacy of admins who fill out the FAQs to only include text. Or what do you think? 

Screenshot?
![Bildschirmfoto 2022-05-19 um 10 31 46](https://user-images.githubusercontent.com/30862422/169250889-6be9ed30-adce-45df-a11d-f179ceb6939a.png)

**Comment by phillimorland** [comment]
@hmkay when you say 'again', was it ever removed from the rich text editor previously?

**Comment by hmkay** [comment]
Ah, no, I meant it in the logical order: Headline of FAQ is H2, than each FAQ is a H3 headline, but in the description of each FAQ, one can have an H2 again. That means one can construct one Question (H3) that has H2 headlines and looks weird and is not in the logic of the headlines. Did that make it clearer?

**Comment by fuzzylogic2000** [comment]
We have set the richtext features (and disabled the h4) in the settings for the whole site. But I think, we can also set it for this field specifically?!

**Comment by phillimorland** [comment]
@hmkay @maxliqd so as this is a richtext element we do have the help-text string, so is this still an issue? or do you want to update the wording of helptext?

**Comment by maxliqd** [comment]
@hmkay I think it is fine as @phillimorland suggests. Would close the issue.

**Comment by hmkay** [comment]
yes, think so, too!
