### ISSUE TITLE
Missing H2 on Quote

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#465]
**URL:** https://gd-dev.liqd.net/
**Comment/Question:** *I couldn't find the H2 for the Quote. Is that how it supposed to be?* 

<img width="1263" alt="Screenshot 2022-05-23 at 16 50 31" src="https://user-images.githubusercontent.com/59610786/169847576-be481cf8-0537-4079-b08b-4f952c12e577.png">

**Comment by phillimorland** [comment]
`blockquote` is a special html element so doesn't need a headline of it's own as it's kind of self explanatory to a SR also we follow their styling precisely with this one
