### ISSUE TITLE
breadcrumbs language

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#475]
**URL:** gemeinsamdigital.berlin.de
**user:** English speaking user, user Leichte Sprache
**expected behaviour:** Breadcrumps show page title in right language.
**behaviour:** Breadcrumps are in German.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Use Page title EN for English breadcrumbs
Use Page title LS for LS breadcrumbs
Nice to have: Keep using title from common tab for German breadcrumbs because it allows for shorter breadcrumbs
Nice to have: Add "displayed as breadcrumbs for German/ English/ Leichte Sprache" on Wagtail

Screenshot?

<img width="611" alt="image" src="https://user-images.githubusercontent.com/94360651/172351373-ba34a0db-2759-4d35-b395-21b426dedb40.png">

**Comment by philli-m** [comment]
NOTE: take translated title instead of page title
