### ISSUE TITLE
[GDB] unexpected scroll-down buttons next to h2 headlines

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#487]
**URL:** https://gemeinsamdigital.berlin.de/ https://gd-stage.liqd.net/ergebnisse/
**user:** visitor
**expected behaviour:** non-scrollable buttons
**behaviour:** Scroll-down buttons suddenly there
**important screensize:** desktop mobile
**device & browser:** safari, chrome
**Comment/Question:** 

Screenshot?
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/94360651/184135811-d984877b-ac0c-44bf-8e95-721ea89e6a17.png">

**Comment by maxliqd** [comment]
Also on teaser tiles, looks really funny: 
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/94360651/184600276-dcad81a7-d911-4cc8-8d96-24c9b5188fe0.png">

**Comment by phillimorland** [comment]
NOTE: style guide has overflow auto everywhere which causes scroll, we need `overflow:hidden;` however explicitly setting this could be an issue?! will need testing
