### ISSUE TITLE
teaser tiles char limit too big for tile

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#495]
**URL:** https://gd-stage.liqd.net/ma%C3%9Fnahmen-index/
**user:** cms editor
**expected behaviour:** The text I insert in the field for tile title is not too long to break the styling
**behaviour:** Tile title too long
**important screensize:**desktop 1920
**device & browser:** mac, chrome
**Comment/Question:** 
@mcastro-lqd Would a char limit of 48 work from your perspective?
Screenshot?
![image](https://user-images.githubusercontent.com/94360651/190654707-b99f0201-6b2b-42a6-a0e4-b2ee6b8a3789.png)

**Comment by fuzzylogic2000** [comment]
So, we should limit the char length to 48? Or do we need to wait for a decision?

**Comment by maxliqd** [comment]
@fuzzylogic2000 I checked dev again, I think you already fixed this block before by reducing the size of black button for the arrow: 
![image](https://user-images.githubusercontent.com/94360651/200300157-cbc8a868-3894-4c2d-bf98-455e922e2b2d.png)
