### ISSUE TITLE
spacing between blocks irregular

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#496]
**URL:** https://gd-stage.liqd.net/ma%C3%9Fnahmen-index/
**user:** visitor
**expected behaviour:** spacing between blocks is similar
**behaviour:** Sometimes a lot (between two paragraph blocks, sometimes very little (between single teaser and teaser tiles
**important screensize:**desktop
**device & browser:** 
**Comment/Question:** 
@mcastro-lqd Is this spacing correct?
Screenshot?

Desktop, two paragraph block, teaser tiles
![image](https://user-images.githubusercontent.com/94360651/190658178-250717fc-9f93-43d9-849c-1a29bae6de34.png)

Mobile, two paragraph blocks

![image](https://user-images.githubusercontent.com/94360651/190657797-766889b5-ef38-444c-bbce-0a9f03bbd65f.png)

**Comment by mcastro-lqd** [comment]
@maxliqd no, it should have that much of a space between them. They are like here: https://zpl.io/Dl6LmQr

**Comment by phillimorland** [comment]
related https://github.com/liqd/digitalstrategie/issues/492

**Comment by phillimorland** [comment]
added extra padding to `ds-block for when it has bg colour, need to not add to non bg colour blocks

**Comment by maxliqd** [comment]
We are only using colour in these blocks: Teaser centered, teaser image, newsletter block, if this information helps somehow
