### ISSUE TITLE
padding and image size single teaser on 800x600 screens

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#533]
**URL:** https://gd-stage.liqd.net/data-governance/
**user:** visitor
**expected behaviour:** coherent padding and image size for teaser single
**behaviour:** Whilst teaser columns has padding around the block, teaser single does not.
**important screensize:** 694 x 768, 800 x 600, ipad (normal)
**device & browser:** chrome, firefox, safari
**Comment/Question:** 

Screenshot?

https://gd-stage.liqd.net/warum-gemeinsam-digital-berlin/

<img width="821" alt="image" src="https://user-images.githubusercontent.com/94360651/199215604-d67bc136-a4f5-422c-b882-9f854af91b76.png">

https://gd-stage.liqd.net/data-governance/
<img width="773" alt="image" src="https://user-images.githubusercontent.com/94360651/199238529-047ffbe9-ae14-4ac2-9d68-2691ad88de79.png">

**Comment by phillimorland** [comment]
@maxliqd these links are for stage, can you add links to dev? also just fyi stage is kept in the same state as prod so does not reflect the most recent changes to the code, only dev shows the state the code is currently in so all testing of stories and for release should happen on dev After we do the stage release we will tag you for stage testing. cheers!

**Comment by maxliqd** [comment]
https://gd-dev.liqd.net/de/

![image](https://user-images.githubusercontent.com/94360651/200297129-b6f2bec1-7b7b-4740-85a1-cebd4727d3d0.png)

**Comment by maxliqd** [comment]
![image](https://user-images.githubusercontent.com/94360651/200297165-bf948cdc-8e9a-4a10-85fa-f1b30c091dea.png)
