### ISSUE TITLE
check if newsletter block success page works with language url

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/digitalstrategie#546]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** As subscribing to the newsletter does not currently work on dev, we could not test it so far. Steps to do:

- [ ] 1. @maxliqd checks if the token should work and replaces it by a working one if need be
- [ ] 2. the devs check the newsletter block is working and the success message makes sense with the language (the newsletter success url is currently not added to the language-urls, so it will not contain /en, /de or /de-ls)

Screenshot?

**Comment by maxliqd** [comment]
This is what I get, when I insert my email
![image](https://user-images.githubusercontent.com/94360651/200546501-d8e1b30a-b06f-4910-a56d-1515c2774e8f.png)
![image](https://user-images.githubusercontent.com/94360651/200546851-adfe606f-36bd-4bf2-9f4d-354b242c22fb.png)

The following success page doesn't work: 
![image](https://user-images.githubusercontent.com/94360651/200547150-16768df0-015b-48d3-b94a-1a3cbcbdd781.png)

I can copy the API code for again and I can also generate a knew key, if that is what you need.

**Comment by fuzzylogic2000** [comment]
@maxliqd But this is still broken, right?

**Comment by maxliqd** [comment]
@fuzzylogic2000: @goapunk told me it is working again. I tested it too.

**Comment by fuzzylogic2000** [comment]
Ah cool, thanks!

**Comment by goapunk** [comment]
I only tested that the newsletter works to be fair, not the success page.

**Comment by Rineee** [comment]
> @maxliqd Did you change anything? @Rineee got a 500 last week. And how do you see the first image? For me it directly goes to the broken https://gd-dev.liqd.net/newsletter-signup/

Haha, I clicked on the link and it gives a 500 :see_no_evil: But where did you get that link from? The newsletter block is here https://gd-dev.liqd.net/de/%C3%BCber-den-prozess-overview-page/ and after registering you stay on the site?

**Comment by goapunk** [comment]
should be fixed by https://github.com/liqd/digitalstrategie/pull/557
