### ISSUE TITLE
image in block text with image gets cut off on the sides

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#548]
**URL:** https://gd-stage.liqd.net/strategie/kapitel-3-ma%C3%9Fnahmen/
**user:** 
**expected behaviour:** Whole picture of block text with image is shown, picture is the same on desktop and mobile.
**behaviour:** Margins cut off a strip on both sides. Rendering differs.
**important screensize:** mobile (414 x 736), ipad mini
**device & browser:** chrome, safari
**Comment/Question:** 

Screenshot?

![image](https://user-images.githubusercontent.com/94360651/200001707-4def3639-7da0-4cee-952a-99ee294bd3e2.png)

![image](https://user-images.githubusercontent.com/94360651/200002128-1dfa1b13-1d6c-4852-86ae-9a245c74063e.png)

**Comment by phillimorland** [comment]
@maxliqd same as other issue, can you check dev and see if it's still an issue there and add link?

**Comment by maxliqd** [comment]
@phillimorland Issue exists on dev as well:
![image](https://user-images.githubusercontent.com/94360651/200343428-7aa5dbca-2ff2-45f0-9154-679e927c5ad1.png)

**Comment by maxliqd** [comment]
![image](https://user-images.githubusercontent.com/94360651/200343729-985b27e8-8bd1-4da4-b8fe-4f3be6faf04b.png)

**Comment by maxliqd** [comment]
And here's the link: https://gd-dev.liqd.net/de/glossary/
