### ISSUE TITLE
Redirect and Canonical 

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#606]
**Essential Information**
Either there is a redirect at two possible URLs (with and without "www"), or a canonical is correctly set via HTTP headers or HTML meta tags.
**URL:** gemeinsamdigital.berlin.de
**device & browser:**
**operating system (incl. version):**
**behaviour:**  
https://gemeinsamdigital.berlin.de -> https://gemeinsamdigital.berlin.de/en/
https://gemeinsam-digital.berlin.de -> https://gemeinsamdigital.berlin.de/
https://www.gemeinsamdigital.berlin.de -> https://www.gemeinsamdigital.berlin.de/
https://gemeinsam-digital.berlin.de -> https://gemeinsamdigital.berlin.de/
https://www.digitalstrategie.berlin.de -> https://digitalstrategie.berlin.de/
https://digitalstrategie.berlin.de -> https://gemeinsamdigital.berlin.de/
**expected behaviour:**
For www.digitalstrategie two redirects are triggered, it could be redirected directly to gemeinsamdigital.berlin.de
**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
@maxliqd I am unsure what we want doing here, I think we want the following redirects set
www.digitalstrategie => https://gemeinsamdigital.berlin.de/
digitalstrategie =>  https://gemeinsamdigital.berlin.de/

I that correct? and is the current behavior that is listed fine?
As for Canonical tags, these are used to indicate which page should be indexed if there are similar pages (they specify the main page) so do we also want to set the canonical tags to indicate https://gemeinsamdigital.berlin.de/ is the main page that should be indexed for all those urls?

**Comment by maxliqd** [comment]
@philli-m This is what they wrote as well about the expected behaviour in the audit: "Either there is a redirect at two possible URLs (with and without "www"), or a canonical is correctly set via HTTP headers or HTML meta tags." If that is illuminating.

**Comment by maxliqd** [comment]
And yes, we probably want https://gemeinsamdigital.berlin.de/ to be tagged as the main page

**Comment by goapunk** [comment]
I changed the redirect from https://www.digitalstrategie.berlin.de/ -> https://digitalstrategie.berlin.de/ to https://www.digitalstrategie.berlin.de/ -> https://gemeinsamdigital.berlin.de. Apart from that we don't need to fix anything here I think, https://gemeinsamdigital.berlin.de/ is already the main site
