### ISSUE TITLE
Captcha not conforming to styleguide

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#611]
**Essential Information** Captcha should be in line with styleguide, but there is no captcha service in styleguide
**URL:** https://gemeinsamdigital.berlin.de/en/kontaktformular/
**device & browser:**
**operating system (incl. version):**
**behaviour:** Captcha not in styleguide
**expected behaviour:** Captcha in line with styleguide

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
no captcha service is available in styleguide, other options are expensive or few  GDPR and a11y compliant
**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
@maxliqd what should we do here?

**Comment by maxliqd** [comment]
@philli-m I will inquire if there is a captcha in the styleguide. @goapunk hadn't found one. We probably cannot do anything right now.

**Comment by goapunk** [comment]
@maxliqd I will close this as we don't have to change anything, right? Otherwise feel free to reopen
