### ISSUE TITLE
CSRF-Tokens

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#615]
**Essential Information**
**URL:**
**device & browser:**
**operating system (incl. version):**
**behaviour:** 
CSRF tokens are set by cookie, but not used in the search form
Contact form uses a CSRF token.
If you set the cookie "csrftoken" in the request, the same token is used again as cookie in the response. A test via Curl shows that a combination of cookie and matching "csrfmiddlewartoken" can be reused on another client.
**expected behaviour:**

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
A search form does not necessarily have to use a CSRF token, so no negative evaluation.

We recommend to set the CSRF cookie only if it is needed.

It should be checked urgently whether the CSRF implementation really protects against request forgery.
**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by goapunk** [comment]
As stated we don't need a CSRF token for the search and there is also no real reason to have one for a public search. Regarding the check of the CSRF implementation, we also don't need to do anything as we use the django csrf protection as intended. Will close this
