### ISSUE TITLE
Update teaser tiles to new version "icon tiles" from styleguide

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#618]
**Essential Information**
**URL:** gemeinsamdigital.berlin.de
**device & browser:**
**operating system (incl. version):**
**behaviour:** Teaser tiles deviate from styleguide
**expected behaviour:** Should be updated to icon tiles, to be found in newest version of styleguide

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
Check whether there are any changes apart from new class name "icon tiles", there shouldn't be any affecting the styling.
Related issue: https://github.com/liqd/digitalstrategie/issues/617
Old issue (closed because very similar but also confusing): https://github.com/liqd/digitalstrategie/issues/407

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by maxliqd** [comment]
Checked the styleguide, they changed the icon tiles to three columns. We are already using them in various places with four columns. Ideally, we would keep four columns.

**Comment by fuzzylogic2000** [comment]
fixed by #719
