### ISSUE TITLE
7283 measures detail page char limit for field website

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#667]
**Essential Information** there is a char limit for the website field, should not be there as it shortens the inserted URL
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/smart-space-hardenbergplatz/
**device & browser:**
**operating system (incl. version):**
**behaviour:**
**expected behaviour:** 

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

![image](https://user-images.githubusercontent.com/94360651/234333474-07c380d0-fd2e-4744-bd41-fd0ce51e7280.png)

**Comment by fuzzylogic2000** [comment]
We couldn't remove the limit, but will use 2000 instead of 20 now, that should be long enough for any case.
