### ISSUE TITLE
7283 measures detail page text field with image: wrap text around image

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#669]
**Essential Information** Text should wrap around image
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/smart-space-hardenbergplatz/
**device & browser:**
**operating system (incl. version):**
**behaviour:** text is in separate column
**expected behaviour:** text wraps around image

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

Design: 
![image](https://user-images.githubusercontent.com/94360651/234534983-0429fa39-1f2f-4327-9653-3087941cdeab.png)

**Comment by fuzzylogic2000** [comment]
To me it looks like it only happens for bullet points or enumerations, which does make sense. Or does it also happen for normal text?

**Comment by fuzzylogic2000** [comment]
Uh, I didn't know it works elsewhere. And I have no idea how hard or easy it is. @philli-m has to say.
(And the word is also a bit broken: the space below the dots is missing next to the image. So, maybe not using bullet points with left aligned images is the best solution. :))

**Comment by philli-m** [comment]
@maxliqd I had a bit of a play and without changing their structures and adding a custom thing for our richtext text in wagtail we cannot do it and it would just mean possible having additional issues when they change their styling so I think it is best if we can just adapt the content, as such I will close, sorry!

**Comment by maxliqd** [comment]
@philli-m Thanks for your efforts, I agree with you.
