### ISSUE TITLE
7238 measures detail page spacing table and picture + paragraph 

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#671]
**Essential Information** spacing between table for organisation etc. and picture and paragraph is a bit crammed
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/smart-space-hardenbergplatz/
**device & browser:** firefox, chrome, especially desktop
**operating system (incl. version):**
**behaviour:** 
**expected behaviour:** a little more space, see design

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

Issue:
![Issue Spacing MDP](https://user-images.githubusercontent.com/94360651/234611968-83c23749-0bae-403c-8c00-0bec2aabf78b.jpg)

Design:
![image](https://user-images.githubusercontent.com/94360651/234612223-5448972d-c5b2-4c48-9c7f-9e4a8af15f50.png)

**Comment by philli-m** [comment]
@maxliqd this seems fixed, please re-open if not!
