### ISSUE TITLE
7260 measures overview page char limit body swiper

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#678]
**Essential Information** no char limits, text can be too long for desktop
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/
**device & browser:** chrome, desktop
**operating system (incl. version):**
**behaviour:**
**expected behaviour:** 
add char limits
Title: 100
Body: 285
Link text: 35 

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/94360651/234791146-7d67b76a-3069-414b-a611-b33a680fdaac.png">

**Comment by fuzzylogic2000** [comment]
We use these blocks in more places then here. Current char limits are:
title: 130
body: 500
link text: 50

Same title and body are also used in the teaser block column for the columns. The Link block and thus that char limit are used basically everywhere where we have a link with a link text. So, if we change it, it will affect all of these places. Should we still do that?

**Comment by maxliqd** [comment]
In that case don't change them. We will keep that in mind when we write the texts.
