### ISSUE TITLE
7260 measures overview page tiles

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#679]
**Essential Information** styling of tile not correct
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/ 
**device & browser:** desktop and mobile
**operating system (incl. version):**
**behaviour:**
**expected behaviour:**
Alle categories in separate line, currently comma is separating the last two
Show copyright of image

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/94360651/234795138-7dd88b14-39e1-4f49-8092-4e95dd05d263.png">

**Comment by fuzzylogic2000** [comment]
Fixed already!
