### ISSUE TITLE
Short name "Easy Language" in German

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#68]
**URL:** https://digitalstrategie-dev.liqd.net/
**user:** participant

**Comment/Question:** How do we display "Easy Language" as a short version? What would be a good name? Can we display it in a long way? Does anybody have an idea also with reference to accessibility?

![Bildschirmfoto 2021-10-11 um 17 38 01](https://user-images.githubusercontent.com/30862422/136817856-67f69c14-0fb0-42f4-b661-4ad4646c805a.png)

**Comment by Rineee** [comment]
@hmkay I dont know, it was your question :sweat_smile: But the content of the dropdown will stay the same I guess, also in the new header. 
So your question is if we should display the selected language not with the language code, but the whole word instead, right?

**Comment by hmkay** [comment]
nice, thank you! That will be fine, @Rineee and @khamui !
