### ISSUE TITLE
7260 measure overview page spacing filter tile

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#680]
**Essential Information** no spacing between filter and first tile
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/
**device & browser:** mobile
**operating system (incl. version):**
**behaviour:**
**expected behaviour:**
add spacing according to design 

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

Issue
![issues mop spacing](https://user-images.githubusercontent.com/94360651/234799484-646c6420-0e82-40bb-bfb4-94ee33384560.jpg)

 Design
<img width="395" alt="image" src="https://user-images.githubusercontent.com/94360651/234796934-c4e3d15d-4788-41d9-b475-fa4145b1b3e3.png">

**Comment by fuzzylogic2000** [comment]
Will close as with the measures count, that count will always be there and thus space.
