### ISSUE TITLE
7260 measure overview page pagination shows incorrect number of pages

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#683]
**Essential Information** Despite all tiles being displayed page one, the pagination indicates there are 15 pages
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/
**device & browser:** chrome
**operating system (incl. version):**
**behaviour:** more pages in pagination than actually exist
**expected behaviour:** pagination reflects number of pages that exist

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.
![image](https://user-images.githubusercontent.com/94360651/235098632-d0f6c630-7c59-4fd7-a2ca-d37347fbf45e.png)

**Comment by fuzzylogic2000** [comment]
That was when the pagination wasn't implemented yet, should be fine now.
