### ISSUE TITLE
7621 filter for fields of action collapsed in load state and after filtering.

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#699]
**Essential Information** The filters for fields of action are collapsed in load state and after filtering.
**URL:**https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/?page=1
**device & browser:**
**operating system (incl. version):**
**behaviour:** Fields of action are collapsed
**expected behaviour:**All filters should be expanded/ not collapsed so you can see the categories.

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
Related issue: #698 

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
Because of issue #698, I understood that the field of action filters should be open only after filtering and fixed that. But they should always be open when the measures overview page is openend on desktop?
