### ISSUE TITLE
7264 LS pages with no content blocks in body show blocks from other languages

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#706]
**Essential Information** When the language tab for Leichte Sprache has no blocks in the body, blocks from German are served, although title and page introduction are filled in.
**URL:** https://gd-dev.liqd.net/de-ls/mitmachen/
**device & browser:** firefox, chrome
**operating system (incl. version):**
**behaviour:** Wrong block shown
**expected behaviour:**only blocks in Leichte Sprache tab get shown

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by Rineee** [comment]
@maxliqd I am not sure I get what you mean. To me this sounds like the right behaviour: user selects 'Leichte Sprache' -> title and page introduction are shown in leichte Sprache, body is shown in German (the fallback language) as there is no content in Leichte Sprache.

**Comment by Rineee** [comment]
> @maxliqd I am not sure I get what you mean. To me this sounds like the right behaviour: user selects 'Leichte Sprache' -> title and page introduction are shown in leichte Sprache, body is shown in German (the fallback language) as there is no content in Leichte Sprache.

Reading this again, I think the confusion might be, that we do the language serving 'field by field' and not for the whole page. So, we decide for every field if there is content in the chosen language and if not, the default language is shown.

**Comment by maxliqd** [comment]
@Rineee Ok thanks, I don't think it is a big problem in practice, we can always add a paragraph block in Leichte Sprache

**Comment by maxliqd** [comment]
@Rineee This issue popped up again on stage. I had hoped it would not... The page intro from DE gets shown on LS and EN. You can only prevent this by filling in content into the intro text field LS or EN. This makes all fields somehow mandatory in LS and EN to fill in the content. https://gd-stage.liqd.net/en/strategie/ and https://gd-stage.liqd.net/de-ls/strategie/

**Comment by goapunk** [comment]
@maxliqd what do you propose as a solution? Disable the fallback language and show nothing/empty block instead?

**Comment by maxliqd** [comment]
@goapunk Can you serve the language for the page instead of field by field? Let me know if that is complicated. I am unsure about disabling the fallback language and which wider implications this would have.

**Comment by Rineee** [comment]
> @goapunk Can you serve the language for the page instead of field by field? Let me know if that is complicated. I am unsure about disabling the fallback language and which wider implications this would have.

Hm, it is possible, but I think quite some work.. so with serving language by page, you mean 
- show default language only if none of the pages fields have content in the selected language
- otherwise (at least one field is filled in selected language) show content in selected language (empty fields included)
Is that right? I think this would rather be a story than issue fixing tbh :grimacing: Or what do you think @fuzzylogic2000 @philli-m ?

**Comment by philli-m** [comment]
@maxliqd should this still be something we look at?

**Comment by philli-m** [comment]
notes: 
create oveview page
- fill out title, de page title and meta and add image 
   - de shows
   - en shows german 
   - ls reverts to home page
- fill out intro de    
    - de shows
   - en shows german 
   - ls reverts to home page
- fill out blocks
    - de shows
   - en shows german 
   - ls reverts to home page
- fill out ls title - saves - shows ls title, de intro, de blocks 
- fill out ls intro - saves - shows ls title and into, de block
- fill out ls block - saves - shows ls title, intro and block, no de content
   -

**Comment by philli-m** [comment]
Current state is each page requires a page title, intro and at least 1 block to ensure only that language is shown

**Comment by philli-m** [comment]
@maxliqd and if it is still something we should fix, what do you want us to do? I think most of the options would be more a user story then issue fix as this is intended behavior and I don't know how to change it, maybe @goapunk knows better?

**Comment by maxliqd** [comment]
@philli-m I think we can close it, as it is not high prio and would be quite some work, if I understood rine correctly.
