### ISSUE TITLE
7361 Filter no anchor link for filter results

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#711]
**Essential Information** When you have filtered, you jump back to the top of the page but not to the filter results, so you don't see them immediately.
**URL:**https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/?status=&district=7
**device & browser:**desktop, mobile
**operating system (incl. version):**
**behaviour:** not jumping to results after filtering
**expected behaviour:** you  jump to the top

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by maxliqd** [comment]
@philli-m Is this rather a story?

**Comment by philli-m** [comment]
@maxliqd no, the adding of the anchor link is very easy and I assume that tagging that onto the url won't be hard either depending on how we filtered right @fuzzylogic2000
