### ISSUE TITLE
gd-dev.liqd.net not working on Safari

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#727]
**Essential Information**
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/titel/
**device & browser (incl version):** *Safari - Version 16.4 (18615.1.26.110.1)*
**operating system (incl. version):** macOS 13.3.1 Ventura

Ive already tried cleaning Cache
<img width="1396" alt="Screenshot 2023-05-17 at 08 51 36" src="https://github.com/liqd/digitalstrategie/assets/59610786/4a790493-369d-4ad1-89df-b1667deebab0">

**Comment by goapunk** [comment]
fixed the broken csp
