### ISSUE TITLE
#7261 [GDB] Filter Measures

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#729]
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/
**device & browser (incl version):** *Safari & Chrome*
**operating system (incl. version):** macOS 13.3.1 Ventura, iOS 16.4.1
**behaviour:** *Describe the issue*
**important screensize:** *Both*
**Comment/Question:** *I have added everything in this pdf. Thanks*
[230517-massnahmen.pdf](https://github.com/liqd/digitalstrategie/files/11499187/230517-massnahmen.pdf)

**Comment by fuzzylogic2000** [comment]
- [ ] decreace spacing between headline and subheadline
- [ ] last line of swiper block is cut off
- [ ] only show x in search when there is a search term
- [ ] check dropdwon arrow - seems to be too small
- [ ] check header structure
- [ ] mobile: swiper dots missing
- [ ] mobile: check spacing between filter and image

**Comment by philli-m** [comment]
@maxliqd @mcastro-lqd the issue with cutting off of text on the swiper is because we used the image link block which has a char limit of 500 but I think we need less here, I think around 400, do that sound ok?

**Comment by philli-m** [comment]
oh and @mcastro-lqd the no dots on mobile I can't reproduce, was this on your device or on responsive mode in browser?

**Comment by fuzzylogic2000** [comment]
> @maxliqd @mcastro-lqd the issue with cutting off of text on the swiper is because we used the image link block which has a char limit of 500 but I think we need less here, I think around 400, do that sound ok?

@philli-m We discussed that here: https://github.com/liqd/digitalstrategie/issues/678
But I guess with the cut-off problem, we need to make it shorter? And we could also if we absolutely need the 500 for the others make it's own field for this swiper block.

**Comment by maxliqd** [comment]
@philli-m @fuzzylogic2000 These char limits should work well for the new swiper, I tested them, see #678: 
Title: 100
Body: 285
Link text: 35

**Comment by mcastro-lqd** [comment]
@philli-m Somehow the dots are showing now for me. So forget about it 
Thanks
