### ISSUE TITLE
Translated breadcrumbs are too long

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/digitalstrategie#745]
**Essential Information**
**URL:** https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/measures-detail-page-6/
**device & browser:**
**operating system (incl. version):**
**behaviour:** The (translated) page titles can be very long, that looks weird as a breadcrumb
**expected behaviour:** The breadcrumbs should be fairly short.

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:** Should we just cut them off like after 50 characters? @mcastro-lqd @maxliqd 

![image](https://github.com/liqd/digitalstrategie/assets/8178179/751eed58-9959-4483-bbb5-16bc522316ae)

**Comment by maxliqd** [comment]
@fuzzylogic2000 It makes sense to me to cut the single breadcrumb of a page to 50. Should we add three dots at the end?
