### ISSUE TITLE
7360 and 7361 Meta tags title not in use on start page and overview page

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#749]
**Essential Information** The page title is being shown on social media preview, not the meta tag title. On start page and overview. I works on grünbuch and microsite overview.
**URL:**
start page
https://gd-dev.liqd.net/en/
overview page
https://gd-dev.liqd.net/en/%C3%BCber-den-prozess-overview-page/

GB overview
https://gd-dev.liqd.net/en/gr%C3%BCnbuch-overview-page/
MS overview
https://gd-dev.liqd.net/en/microsite-overview-page/

**device & browser:**
**operating system (incl. version):**
**behaviour:** meta tag title not shown
**expected behaviour:** use meta title for social media preview on start page and overview page

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
@goapunk Noo, it's still there. :( I hoped it would be fixed.

**Comment by philli-m** [comment]
this is not our bug https://github.com/liqd/digitalstrategie/issues/766
