### ISSUE TITLE
landing page doesn't redirect to language, but 500

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/digitalstrategie#769]
**Essential Information**
**URL:** https://gd-dev.liqd.net/
**device & browser:**
**operating system (incl. version):**
**behaviour:**
**expected behaviour:**

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:** Is related to: https://github.com/liqd/digitalstrategie/pull/748/ (obvious because of sentry). But changing the template tag completely back to the old version didn't fix it. Not repsoducable locally. 

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
@fuzzylogic2000 I cannot reproduce this, is it still an issue?

**Comment by fuzzylogic2000** [comment]
Oh sorry, was fixed by #771
