### ISSUE TITLE
server settings,  logfiles and csrf token storage durartion

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#805]
**Essential Information** 
**URL:**
**device & browser:**
**operating system (incl. version):**
**behaviour:** logfiles are saved for 30 days, csrf token for 7
**expected behaviour:** save for 5 days only

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by goapunk** [comment]
done
