### ISSUE TITLE
Icon and link for Leichte Sprache in footer of all languages

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#806]
**Essential Information** the icon for Leichte Sprache is not removable from the footer for Leichte Sprache and English. The text is not editable. 
**URL:** https://gd-stage.liqd.net/de-ls
**device & browser:**
**operating system (incl. version):**
**behaviour:** Link with icon is in English and Leichte Sprache footer
**expected behaviour:** Link should only be visible in German version of page

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by goapunk** [comment]
@maxliqd the issue with the leichte sprache button is also when clicking on the accessible/barrierefrei button in the header, does it need to be shown there only in German as well?

**Comment by maxliqd** [comment]
@goapunk

**Comment by maxliqd** [comment]
@goapunk Took a longer look at this, giving you the ideal version here. Happy to go for what's feasible within in your resources. Could also put this in another issue for a later point in time...

Accessible button
- In Leichte Sprache it is not necessary to have the link to Leichte Sprache, the headline "Einstellung" is not necessary either. 
- In DE it should actually link to Leichte Sprache, link does not seem to work right now.
- In EN it should ideally be called Easy German (Leichte Sprache). Other Option: remove as it might be confusing.
Burger Menu
- In Leichte Sprache Deutsch should be called Alltagssprache, English should be called Englisch with a c. Menu item "Barrierefreiheit" with subitem Leichte Sprache could be removed as you are already on that page. 
- In DE English should be Englisch with a c.
- In EN, Leichte Sprache should be called Easy German (Leichte Sprache), Deutsch should be German.

**Comment by philli-m** [comment]
@maxliqd the burger menu should be a different issue and possible a story? i did a quick test and had trouble replicating behaviour but @Rineee experienced different wording to me both in firefox set to english so this might be a more complex issue
