### ISSUE TITLE
empty accordion bodies in older browser versions

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#844]
**Essential Information** in older versions of some browsers content in accordion bodies is not shown, instead there is empty space. All items are expanded.
**URL:** https://gemeinsamdigital.berlin.de/de/handbuch/methoden/
**device & browser:**
- Safari Version 15.3 (17612.4.9.1.8), MacBook Air (M1, 2020), MacOSMonterey 12.2.1
-  Mac, Sierra, Firefox 107
- Windows 11, Firefox 107

**operating system (incl. version):**
**behaviour:** empty accordions 
**expected behaviour:** content should be displayed, only one item should be expanded at a time.

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
Do we need more info on browser versions?
- Older Safari versions cannot be tested on Browserstack
- Firefox from Version 108 is ok
- Chrome is ok, even in Version 87

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
seems to be a CSP issue, no read out in Browserstack but when tested on real machine console:
@goapunk 

```
[Error] Refused to load https://www.berlin.de/i9f/r1/bundle/jquery.min.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load https://www.berlin.de/i9f/r1/bundle/berlin_marketing.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load https://www.berlin.de/i9f/r1/bundle/swiper.min.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load https://www.berlin.de/i9f/r1/bundle/shariff.min.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load https://www.berlin.de/i9f/v4/js/bo-foot-rebrush.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load https://stats.liqd.net/matomo.js because it does not appear in the script-src directive of the Content Security Policy.
```
