### ISSUE TITLE
wrong headline for text field Participation/ Beteiligung 

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#871]
**Essential Information**
**URL:** https://gd-stage.liqd.net/de/massnahmen-der-strategie/test-titel/
**device & browser:**
**operating system (incl. version):**
**behaviour:** "Partizipative Governance und Beteiligung" is headline of text field.
**expected behaviour:** Should be "Beteiligung" / "Participation"

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
@maxliqd this is an incorrect translation in weblate, the wording in the code is 'Participation' also when viewing english page it is correct, if you search in weblate for all instances of 'Participation' you should be able to find and correct it

**Comment by maxliqd** [comment]
Hello @philli-m, 
We need two different translations for participation:
1. One for the filter on the measures overview: EN Participation DE Partizipative Governance und Beteiligung
2. One for the measures detail page H2 text field: EN Participation DE Partizipation
That's where the confusion is coming from^^

**Comment by philli-m** [comment]
@maxliqd oh so I don't know how to tell our sofatware that 2 identical strings should have different translations as it goes against one of the basic rules, is it possible that the English can be different for each? if not i'll look into a hack but can't guarantee it, sorry!

**Comment by maxliqd** [comment]
@philli-m Okidoki, good to know: 

1. One for the filter on the measures overview: EN Participatory Governance DE Partizipative Governance und Beteiligung
2. One for the measures detail page H2 text field: EN Participation DE Partizipation

**Comment by philli-m** [comment]
@maxliqd yey! thank you!
