### ISSUE TITLE
search includes content from password protected sites

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#877]
**Essential Information**
**URL:** gemeinsamdigital.berlin.de
**device & browser:**
**operating system (incl. version):**
**behaviour:** search includes content from pw protected sites
**expected behaviour:**content from pw protected sites should not be included

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by maxliqd** [comment]
https://gemeinsamdigital.berlin.de/de/search/?q=matomo 
https://gemeinsamdigital.berlin.de/de/webseite/
@goapunk

**Comment by maxliqd** [comment]
I also tested that the page preview is visible when you are not logged in the CMS and have not entered the password in the browser previously

**Comment by goapunk** [comment]
this should be fixed
