### ISSUE TITLE
add help text for website link on measures detail page

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#878]
**Essential Information** 
**URL:**https://gd-dev.liqd.net/de/massnahmen-der-strategie-gemeinsam-digital-berlin/digital-neukolln-finished-participation-it-ecosystems/
**device & browser:**
**operating system (incl. version):**
**behaviour:**If you want to add websites for the contact on measures detail pages, www-URLs cause a 404
**expected behaviour:**add help text: Use URL starting with protocol http:// or https://

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
@maxliqd have actually found a solution that just ensure text added is saved as a link so will need checking when it's merged
