### ISSUE TITLE
paragraph block divider line for <hr> not visible on safari 

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#879]
**Essential Information**paragraph block divider line  for html tag hr not visible on safari  <hr> 
**URL:** https://gd-dev.liqd.net/en/testbereich/test-detail-page/
**device & browser:** safari, mac 
**operating system (incl. version):**
**behaviour:**
**expected behaviour:** should be visible like on chrome and firefox

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by maxliqd** [comment]
Still does not work on dev in safari: https://gd-dev.liqd.net/en/testbereich/
Or is it not yet on dev?

**Comment by philli-m** [comment]
@maxliqd working locally so I think it might be the csp changes I added to test them as there's something off with dev, will let you know, sorry for confusion

**Comment by philli-m** [comment]
@maxliqd sorry everything is working now, dev was on a csp testing branch, i'm so sorry! I didn't revert the change before leaving, I didn't know it didn't reset on a new build :(

**Comment by philli-m** [comment]
working now
