### ISSUE TITLE
icon tiles height varies between lines depending on title length

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#902]
**Essential Information**
**URL:** https://gd-dev.liqd.net/en/wagtail-test-october-23-overview-page/
**device & browser:** Mac chrome, firefox
**operating system (incl. version):**
**behaviour:** The height of the tiles is not the same in all lines. If you have a longer title in the first line, and only short ones in the second line, the second line's tile will have a lesser height. 
**expected behaviour:** Height the same across lines, all tiles have the height of the tile with the longest title

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
As the fifth tile is also not as high on mobile, maybe they come in bundles of four?

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.
![image](https://github.com/liqd/digitalstrategie/assets/94360651/760dbaac-423a-422f-a9ad-0c8902ebe090)

![image](https://github.com/liqd/digitalstrategie/assets/94360651/a12ca8a0-1a8d-44bc-9d66-569ab5d518e0)

Fifth tile is smaller on mobile.
![image](https://github.com/liqd/digitalstrategie/assets/94360651/e9827a0b-110b-4a38-a480-a4ab7ef59ad9)

**Comment by philli-m** [comment]
@maxliqd link you added is password protected?

**Comment by maxliqd** [comment]
@philli-m Sorry, removed the password!

**Comment by philli-m** [comment]
@maxliqd this is a BO issue but I guess also an us issue as we first wrote this block, if it were still our block I would refactor it to use grid not flex but as it's not maybe it's better to just do a little hack and make all tiles a minimum height of our max content? what do you think?

**Comment by philli-m** [comment]
@maxliqd this is what it would look like, that ok?
![screenshot(23)](https://github.com/liqd/digitalstrategie/assets/5871230/e0ca09f7-29d8-4731-827f-e6c0ecc763f2)
