### ISSUE TITLE
7774 teaser image background colours not selectd, black 

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#905]
**Essential Information**
**URL:** https://gd-dev.liqd.net/en/wagtail-test-october-23-overview-page/
**device & browser:** mac chrome
**operating system (incl. version):**
**behaviour:** When I don't choose a colour for the background, the background is black
**expected behaviour:**
Two options, easier one can be chosen:
1. Colour should be white, to be in sync with help text
2. Make choosing colour mandatory. Preselect pink, if preselect is necessary.
3. Adapt help text: Choose yellow, pink or purple to ensure CI conformity.

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**
**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.

**Comment by philli-m** [comment]
@maxliqd I think this might be from their style library update, are any other teaser behaving this way?
