### ISSUE TITLE
Text editor crashes when adding spaces after a link.

### ISSUE THREAD

**Issue by sblindow** [liqd/digitalstrategie#956]
**Essential Information**
Text editor crashes when adding spaces after a link.

**URL:**
Occurs universally in text editor where links can be added.

**device & browser:**
Mac, Firefox 120.0.1

**operating system (incl. version):**
macos Sonoma 14.1

**behaviour:**
When spaces are added directly behind a link in the Wagtail text editor, the link text is reduced to a single dot.
Subsequent use of the 'cmd+z' (undo) command multiple times leads to the text editor crashing.

**expected behaviour:**
Adding spaces after a link's text should not alter the text or cause the editor to crash.

**Screenshot if design related**:
Error Message:
![Bildschirmfoto 2023-12-20 um 14 58 27](https://github.com/liqd/digitalstrategie/assets/144320958/79a1e104-24e9-43d2-a35e-c7f6eda579a5)

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow can you check again if this bug is still there?

**Comment by sblindow** [comment]
@CarolingerSeilchenspringer can confirm that the bug is still there (tested prod and stage). Although I have to admit that it's quite specific and wont lead to any major problems.

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow thanks, I suggest we look into it and see if it is an easy fix.

**Comment by goapunk** [comment]
I assume this is not our bug, the text editor in wagtail is part of wagtail. I'l see if I can find more info about it

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk if not our bug you can close this issue. thanks

**Comment by goapunk** [comment]
I can't seem to reproduce it on dev anymore maybe you can confirm it's gone @sblindow ?

**Comment by sblindow** [comment]
@goapunk Seems to be fixed, I can't reproduce it on dev either

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow thanks, will close issue, @goapunk
